package com.gmail.goosius.siegewar.settings;

public enum ConfigNodes {

	VERSION_HEADER("version", "", ""),
	VERSION(
			"version.version",
			"",
			"# This is the current version.  Please do not edit."),
	LAST_RUN_VERSION(
			"version.last_run_version",
			"",
			"# This is for showing the changelog on updates.  Please do not edit."),
	WAR("war","","",""),
	WAR_SIEGE(
			"war.siege",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Siege-War settings                 | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_SWITCHES(
			"war.siege.switches",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                       Switches                       | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_ENABLED(
			"war.siege.switches.enabled",
			"true",
			"",
			"# If true, the Siege-War system is enabled.",
			"# if false, the Siege-War system is disabled."),
	WAR_SIEGE_CONQUEST_SIEGES_ENABLED(
			"war.siege.switches.conquest_sieges_enabled",
			"true",
			"",
			"# If true, then nations can start conquest sieges."),
	WAR_SIEGE_LIBERATION_SIEGES_ENABLED(
			"war.siege.switches.liberation_sieges_enabled",
			"true",
			"",
			"# If true, then nations can start liberation sieges."),
	WAR_SIEGE_REVOLT_SIEGES_ENABLED(
			"war.siege.switches.revolt_sieges_enabled",
			"true",
			"",
			"# If true, then towns can start revolt sieges."),
	WAR_SIEGE_SUPPRESSION_SIEGES_ENABLED(
			"war.siege.switches.suppression_sieges_enabled",
			"true",
			"",
			"# If true, then nations can start suppression sieges."),
	WAR_SIEGE_ABANDON_ENABLED(
			"war.siege.switches.abandon_enabled",
			"true",
			"",
			"# If true, then attackers can abandon sieges."),
	WAR_SIEGE_SURRENDER_ENABLED(
			"war.siege.switches.town_surrender_enabled",
			"true",
			"",
			"# If true, then defenders can surrender sieges."),
	WAR_SIEGE_INVADE_ENABLED(
			"war.siege.switches.invade_enabled",
			"true",
			"",
			"# If true, then invasions are enabled."),
	WAR_SIEGE_PLUNDER_ENABLED(
			"war.siege.switches.plunder_enabled",
			"true",
			"",
			"# If true, then plunder is enabled.",
			"# This action will steal money from the town, and transfer it to the victorious nation.",
			"# The below setting of war.siege.money.attacker_plunder_distribution_ratio determines the nation-bank/soldiers distribution",
			"# If the town does not have sufficient funds, it will be bankrupted/ruined/destroyed."),
	WAR_SIEGE_MILITARY_SALARY_ENABLED(
			"war.siege.switches.military_salary_enabled",
			"true",
			"",
			"# If true, then a king can pay their soldiers using '/sw nation paysoldiers <total amount>'.",
			"# The amount will be distributed among the soldiers according to their ranks.",
			"# The permission of siegewar.nation.siege.pay.grade.x, determines how much a rank is paid. x=100 is a normal share, x=200 is double"),
	WAR_SIEGE_CLAIMING_DISABLED_NEAR_SIEGE_ZONES(
			"war.siege.switches.claiming_disabled_near_siege_zones",
			"true",
			"",
			"# If true, then land cannot be claimed near a siege zone.",
			"# This setting is generally considered critical, otherwise one side could wall off the siege zone."),
	WAR_SIEGE_NON_RESIDENT_SPAWN_INTO_SIEGE_ZONES_OR_BESIEGED_TOWNS_DISABLED(
			"war.siege.switches.non_resident_spawn_into_siegezones_or_besieged_towns_disabled",
			"true",
			"",
			"# If this setting is true, then only town residents are permitted to spawn into siegezones OR besieged towns.",
			"# This setting is recommended to:",
			"# 1. Protect players from accidentally spawning into a warzone while unprepared.",
			"# 2. Discourage 'fake' sieges, by making the automatic siege impact harsher.",
			"# 3. Even the spawn-advantage between attacking and defender."), 
	WAR_SIEGE_BESIEGED_TOWN_RECRUITMENT_DISABLED(
			"war.siege.switches.besieged_town_recruitment_disabled",
			"true",
			"",
			"# If this value is true, then a town under active siege cannot recruit new residents.",
			"#  This setting is recommended because it helps discourage 'fake' sieges just for the purpose of of gifting immunity."),
	WAR_SIEGE_BESIEGED_TOWN_CLAIMING_DISABLED(
			"war.siege.switches.besieged_town_claiming_disabled",
			"true",
			"",
			"# If this value is true, then a town under active siege cannot claim new plots.",
			"#  This setting is recommended because it helps discourage 'fake' sieges just for the purpose of of gifting immunity."),
	WAR_SIEGE_BESIEGED_TOWN_UNCLAIMING_DISABLED(
			"war.siege.switches.besieged_town_unclaiming_disabled",
			"true",
			"",
			"# If this value is true, then a town under active siege cannot unclaim.",
			"#  This setting is recommended if invasion/occupation is enabled, to avoid occupation escape exploits."),
	WAR_SIEGE_BESIEGED_TOWN_CANNOT_CHANGE_KING(
			"war.siege.switches.besieged_capitals_cannot_change_kings",
			"false",
			"",
			"# If this value is true, then a town which is a capital of a nation that is under siege, cannot",
			"# change capital to another city via /n set king|capital."),
	WAR_SIEGE_NATION_STATISTICS_ENABLED(
			"war.siege.switches.nation_statistics_enabled",
			"true",
			"",
			"# If this setting is true, then Siegewar statistics will be shown on nation status screens."),
	WAR_SIEGE_KILL_PLAYERS_WHO_LOG_OUT_IN_SIEGE_ZONES(
			"war.siege.switches.kill_players_who_log_out_in_siege_zones",
			"true",
			"",
			"# If this value is true then players who log out in Siege-Zones will be killed.",
			"# TIP 1: This setting is important to prevent reinforcements/ambushers appearing unnaturally in SiegeZones.",
			"# TIP 2: The setting is essential when using the Wall Breaching feature, to stop players logging in/out at the homeblock"),
	WAR_SIEGE_UNJAIL_RESIDENTS_WHEN_ATTACKERS_WIN_SESSION(
			"war.siege.switches.unjail_residents_when_attackers_win_battle_session",
			"false",
			"",
			"# When true, if an attackers wins the battlesession against a sieged town, that",
			"# town's jailed players that belong to the attacking nation will be freed from the town's jail."),
	WAR_SIEGE_GLOWING(
			"war.siege.switches.enabled_glowing_on_players",
			"true",
			"",
			"# When true, players will have a glowing effect."),

	WAR_SIEGE_MONEY(
			"war.siege.money",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                       Money                          | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_ATTACKER_COST_UPFRONT_PER_PLOT(
			"war.siege.money.attacker_cost_upfront_per_plot",
			"20.0",
			"",
			"# This value represents the siege deposit paid by the attacker",
			"# This is the 'warchest' (a money-account, not an actual chest object).",
			"# If the attacking nation wins the siege, the warchest is returned to the nation bank.",
			"# If the defending town wins the siege, the warchest is recovered by the defenders.",
			"# See below for more details on how the warchest is distributed among the defenders."),
	WAR_SIEGE_ATTACKER_PLUNDER_AMOUNT_PER_PLOT(
			"war.siege.money.attacker_plunder_amount_per_plot",
			"40.0",
			"",
			"# This is the amount which an attacking nation will plunder if they choose to do so after a siege victory."),
	WAR_SIEGE_PLUNDER(
			"war.siege.money.plunder","","",""),
	WAR_SIEGE_PLUNDER_PAID_OVER_TIME(
			"war.siege.money.plunder.plunder_paid_over_time",
			"false",
			"",
			"# When true, plunder will function differently, when a town cannot afford to pay the full plunder costs.",
			"# Initially the money is paid to the plunderer in full, from either the Towny server-account (used in closed_economies),",
			"# or else from thin air.",
			"# The money is then paid back on a daily basis from the plundered town, using the set number of days.",
			"# The goal of this system is to make sure that attackers get paid, while giving plundered towns a ",
			"# chance to pay their debt over time."),
	WAR_SIEGE_PLUNDER_DAYS(
			"war.siege.money.plunder.number_of_payments",
			"7",
			"",
			"# When plunder_paid_over_time is true, how many days will the plunder debt be paid over?"),
	
	WAR_SIEGE_CAPITAL_SIEGE_COST_INCREASE_PERCENTAGE(
			"war.siege.money.capital_siege_cost_increase_percentage",
			"0",
			"",
			"# The percentage to increase the cost of sieging capitals by.",
			"# Example: If set to 50, with an attack cost of 20/plot, each plot would be 30."),
	WAR_SIEGE_EXTRA_MONEY_PERCENTAGE_PER_TOWN_LEVEL(
			"war.siege.money.extra_money_percentage_per_town_level",
			"0",
			"",
			"# This value increases the monetary costs & gains of sieges, depending on town level.",
			"# ",
			"# The value is useful to ensure that larger towns/nations will not feel unaffected by war moneys.",
			"# The value is applied to attack cost (war-chest) and plunder.",
			"# The value is appropriate in servers where town wealth does not correspond linearly to number of plots.",
			"# Example: On server x, small towns tend to have 10 plots + 100 gold, and large towns tend to have 100 plots + 999,999 gold.",
			"#          Clearly on this server, wealth is heavily concentrated in larger towns. Thus this value should be high ",
	        "# ",
			"# Example of how this value would affect attack cost (@20/plot), if the value was set to 50 : ",
			"# ",
			"# Level 1 (1 resident), 5 plots. Cost = (20 * 5) + 0% = 100",
			"# Level 2 (3 residents), 15 plots. Cost = (20 * 15) + 50% = 450",
			"# Level 3 (8 residents), 50 plots. Cost = (20 * 50) + 100% = 2000",
			"# Level 4 (12 residents), 80 plots. Cost = (20 * 80) + 150% = 4000",
			"# ",
			"# If the value is 0, then money amounts are not modified."),
	WAR_SIEGE_MAX_PEACEFUL_OCCUPATION_TAX(
			"war.siege.money.max_nation_peaceful_occupation_tax",
			"0",
			"",
			"# The maximum that a nation can set for an peacefuloccupationtax using /n set peacefuloccupationtax.",
			"# This tax is applied to the nation's occupied towns which are peaceful."),

	WAR_SIEGE_QUANTITIES(
			"war.siege.quantities",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |              Non-Monetary Quantities                 | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_MAX_ACTIVE_SIEGE_ATTACKS_PER_NATION(
		"war.siege.quantities.max_active_siege_attacks_per_nation",
		"3",
		"",
			"# The value specifies the maximum number of active attack sieges allowed per nation." +
			"# A low setting will generally reduce the aggression level on the server.",
			"# A low setting will also rebalance the system in favour of smaller nations.",
		 	"# This is because it will prevent larger nations from conducting as many sieges as their resources would otherwise allow."),
	WAR_SIEGE_SIEGECAMPS(
            "war.siege.siege_assemblies",
            "",
            "",
            "",
            "############################################################",
            "# +------------------------------------------------------+ #",
            "# |                    Siege-Assemblies                  | #",
            "# + Siege-Assemblies precede Sieges, when a banner is    | #",
            "# + first placed. By default a 10 minute session in which| #",
            "# + the attacking town must score a given number of      | #",
            "# + points in order to begin a siege. This feature is    | #",
            "# + meant to mitigate towns creating mock-sieges, and    | #",
            "# + using the resulting immunity to avoid sieges by real | #",
            "# + enemies                                              | #",
            "# +------------------------------------------------------+ #",
            "############################################################",
            ""),
	WAR_SIEGE_SIEGECAMPS_ENABLED(
			"war.siege.siege_assemblies.enabled",
			"true",
			"",
			"# When true, SiegeWar will begin each attempted Siege with a Siege-Assembly."),
	WAR_SIEGE_SIEGECAMPS_COOLDOWN(
			"war.siege.siege_assemblies.failed_siege_assembly_cooldown",
			"12h",
			"",
			"# When an attacker fails a Siege-Assembly, how long until they can attempt to attack the town again?"),
	WAR_SIEGE_SIEGECAMPS_POINTS(
			"war.siege.siege_assemblies.points_required_to_succeed",
			"50",
			"",
			"# How many points an attacker must score in a Siege-Assembly to start a siege."),
	WAR_SIEGE_SIEGECAMPS_POINTS_PER_MINUTE(
			"war.siege.siege_assemblies.points_per_minute",
			"7",
			"",
			"# How many points an attacker town gets per minute, when they are present at the Siege-Assembly TimedPointZone."),
	WAR_SIEGE_SIEGECAMPS_DURATION_IN_MINUTES(
			"war.siege.siege_assemblies.duration_in_minutes",
			"10",
			"",
			"# How many minutes does a Siege-Assembly last?"),
	WAR_SIEGE_TIMES(
			"war.siege.times",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                         Times                        | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_MAX_HOLDOUT_TIME_HOURS(
			"war.siege.times.max_holdout_time_hours",
			"72",
			"",
			"# The maximum duration a town can hold out against a siege.",
			"# If the value is too high, regular players may be unsatisfied that sieges take too long.",
			"# If the value is too low, casual players may be unsatisfied that ",
		    "#    they are unable to contribute to sieges, especially those involving their own town/nation"),
	WAR_SIEGE_MIN_SIEGE_DURATION_BEFORE_SURRENDER_HOURS(
			"war.siege.times.min_siege_duration_before_surrender_hours",
			"24",
			"",
			"# The minimum duration of a siege before a town can surrender.",
			"# This setting is important because it prevents a 'quick surrender' by the defender",
			"# - which could leave the attacker with no 'aftermath' time in which to execute invade or plunder actions."),
	WAR_SIEGE_MIN_SIEGE_DURATION_BEFORE_ABANDON_HOURS(
			"war.siege.times.min_siege_duration_before_abandon_hours",
			"24",
			"",
			"# The minimum duration of a siege before an attacking nation can abandon.",
			"# This setting is important to prevent an attacker and defender colluding to establish a suitable siege immunity time."),
	WAR_SIEGE_SIEGE_IMMUNITY_TIME_NEW_TOWN_HOURS(
			"war.siege.times.siege_immunity_time_new_town_hours",
			"120",
			"",
			"# This value determines how long a town is safe from sieges, after the town is founded.",
			"# A high value allows more time to fortify new towns, but community engagement by mayors will be slower.",
			"# A low value allows less time to fortify new towns, but community engagement by mayors will be faster."),
	WAR_SIEGE_SIEGE_IMMUNITY_TIME_MODIFIER(
			"war.siege.times.siege_immunity_time_modifier",
			"3",
			"",
			"# This value determines how long a town is safe from sieges, after a siege finishes.",
			"# The actual cooldown time will be the length of the previous siege, multiplied by this modifer.",
			"# A high value makes sieges less frequent. Suitable for moderately-aggressive servers",
			"# A low value makes sieges more frequent. Suitable for highly aggressive servers."),
	WAR_SIEGE_REVOLT_IMMUNITY_TIME_MODIFIER(
			"war.siege.times.revolt_immunity_time_modifier",
			"0.75",
			"",
			"# This value determines how long a town must wait before it can revolt against an occupying nation.",
			"# Revolt immunity beings after a town is defeated in a siege.",
			"# The configured value represents a fraction of the actual immunity time.",
			"# Note: Revolting can break through siege immunity",
			"# WARNING: Do not set this to any higher than about 0.8, because that could lead to towns getting trapped in an endless cycle of invasions from which they could not free themselves."),
	WAR_SIEGE_BANNER_CONTROL_SESSION_DURATION_MINUTES (
			"war.siege.times.banner_control_session_duration_minutes",
			"7",
			"",
			"# This value determines the duration of each banner control session."),
	WAR_SIEGE_DISTANCES(
			"war.siege.distances",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                      Distances                       | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_ZONE_RADIUS_BLOCKS(
			"war.siege.distances.siegezone_radius_blocks",
			"200",
			"",
			"# The radius of the 'siege zone'.",
			"# This radius applies only horizontally, so players can never get above a siegezone (e.g. to place lava there or something).",
			"# Various siege related effects can apply in this zone e.g. lose points on death, cannot TP in, cannot claim."),
	WAR_SIEGE_BANNER_CONTROL_VERTICAL_DISTANCE_UP_BLOCKS(
			"war.siege.distances.banner_control_vertical_distance_blocks_up",
			"16",
			"",
			"# This is the vertical distance a soldier must be within above the Banner.",
			"# Note that the horizontal distance is always the same as the Towny townblock size."),
	WAR_SIEGE_BANNER_CONTROL_VERTICAL_DISTANCE_DOWN_BLOCKS(
			"war.siege.distances.banner_control_vertical_distance_blocks_down",
			"4",
			"",
			"# This is the vertical distance a soldier must be within below the Banner.",
			"# Note that the horizontal distance is always the same as the Towny townblock size."),
	WAR_SIEGE_POINTS_BALANCING(
			"war.siege.points_balancing",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Points Balancing                     #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_POINTS_BALANCING_BASE_POINTS(
			"war.siege.points_balancing.base_points",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |                    Base Points                         #",
			"# +------------------------------------------------------+ #",
			""),
    WAR_SIEGE_POINTS_BALANCING_BASE_POINTS_BANNER_CONTROL(
			"war.siege.points_balancing.base_points.banner_control",
			"",
			"",
			""),
	WAR_SIEGE_POINTS_BALANCING_BASE_POINTS_BANNER_CONTROL_ATTACKER(
			"war.siege.points_balancing.base_points.banner_control.attacker",
			"10",
			"",
			"# This value determines the number of battle points awarded every SiegeWar-tick (20 seconds) to an attacker with banner-control.",
			"# TIP: Always keep this value at 10, for easier comparison with other server configurations."),
	WAR_SIEGE_POINTS_BALANCING_BASE_POINTS_BANNER_CONTROL_DEFENDER(
			"war.siege.points_balancing.base_points.banner_control.defender",
			"10",
			"",
			"# This value determines the number of battle points awarded every SiegeWar-tick (20 seconds) to a defender with banner-control."),
    WAR_SIEGE_POINTS_BALANCING_BASE_POINTS_DEATHS(
			"war.siege.points_balancing.base_points.deaths",
			"",
			"",
			""),
	WAR_SIEGE_POINTS_BALANCING_BASE_POINTS_BANNER_CONTROL_DEATHS_ATTACKER(
			"war.siege.points_balancing.base_points.deaths.attacker",
			"150",
			"",
			"# This value determines the number of battle points awarded if an attacker dies in a siege zone.",
			"# TIP: Set this value low enough so as not to exclude weak players from sieges, and high enough to avoid banner control being considered too OP."),
	WAR_SIEGE_POINTS_BALANCING_BASE_POINTS_BANNER_CONTROL_DEATHS_DEFENDER(
			"war.siege.points_balancing.base_points.deaths.defender",
			"150",
			"",
			"# This value determines the number of battle points awarded if defender dies in a siege zone.",
			"# TIP: Set this value low enough so as not to exclude weak players from sieges, and high enough to avoid banner control being considered too OP."),
    /*
    TODO - Re-enable when end-of-session rollbacks are implemented.

    WAR_SIEGE_POINTS_BALANCING_WALL_BREACH_BONUS(
			"war.siege.points_balancing.wall_breach_bonus",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |                 Wall Breach Bonus                    | #",
			"# +------------------------------------------------------+ #",
			""),
	WAR_SIEGE_POINTS_BALANCING_WALL_BREACH_BONUS_BATTLE_POINTS(
			"war.siege.points_balancing.wall_breach_bonus.battle_points",
			"250",
			"",
			"# If the wall breaching feature is enabled (in the 'Wall Breaching' config section), this value determines the number of Battle Points awarded by the Wall Breach Bonus.",
			"# To get the bonus, hostile-to-town players must capture the banner first, then get to the homeblock.",
			"# TIP: Players are required to cap first, because otherwise they could log off at the homeblock after getting the bonus, and then in the next session, simply log back in to get the bonus again."),
	*/
	WAR_SIEGE_POINTS_BALANCING_BANNER_CONTROL_REVERSAL_BONUS(
			"war.siege.points_balancing.banner_control_reversal_bonus",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |           Banner Control Reversal Bonus              | #",
			"# +------------------------------------------------------+ #",
			""),
	WAR_SIEGE_POINTS_BALANCING_BANNER_CONTROL_REVERSAL_BONUS_ENABLED(
			"war.siege.points_balancing.banner_control_reversal_bonus.enabled",
			"true",
			"",
			"# If this setting is true, then the Banner Control Reversal Bonus is enabled:",
			"# If enabled, and a team reverses banner control during a battle,",
			"# the base generation rate of timed points is then multiplied by the configured value below (e.g. x3).",
			"# Subsequent reversals increase the rate further by that amount.",
            "# TIP: This feature grants small skilled armies a tactic to win battles against larger unskilled armies,",
            "# Tactic: Wait for the large army to cap the banner, then ambush/counterattack them, grabbing the reversal bonus, and holding the area to net an enhanced cap-point score."),
	WAR_SIEGE_POINTS_BALANCING_BANNER_CONTROL_REVERSAL_BONUS_MULTIPLIER_VALUE(
			"war.siege.points_balancing.banner_control_reversal_bonus.multiplier_value",
			"3",
			"",
			"# This setting determines the strength of the bonus multiplier.",
			"# Example: ",
			"# - Assuming this value is 3,",
			"# - If team A reverses banner control, any cap-points they get after that will be multiplied by 3.",
			"# - If team B re-reverses banner control, any cap-points they get after that will be multiplied by 6."),
	WAR_SIEGE_POINTS_BALANCING_CONTERATTACK_BOOSTER(
			"war.siege.points_balancing.counterattack_booster",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |               Counter-Attack Booster                 | #",
			"# +------------------------------------------------------+ #",
			""),
    WAR_SIEGE_POINTS_BALANCING_COUNTERATTACK_BOOSTER_ENABLED(
			"war.siege.points_balancing.counterattack_booster.enabled",
			"false",
			"",
			"# If this setting is true, then if a player from the banner controlling side dies,",
			"# the death points are increased by a certain percentage.",
            "# TIP: This feature delivers extra balance to battles in which one side is outnumbered by the other."),
	WAR_SIEGE_POINTS_BALANCING_COUNTERATTACK_BOOSTER_EXTRA_DEATH_POINTS_PER_PLAYER_PERCENTAGE(
			"war.siege.points_balancing.counterattack_booster.extra_death_points_per_player_percentage",
			"10.0",
			"",
			"# If the counterattack booster is enabled, this value determines the strength of the boost.",
			"# Example: If this value is 10.0, and there are 3 players on the banner control list, and a player from the banner-controlling side dies,",
			"# then the death points awarded to the attacker will be increased by +30%."),
	WAR_SIEGE_POINTS_SIEGE_BALANCE_CAP(
			"war.siege.points_balancing.siege_balance_cap",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |                  Siege Balance Cap                     | #",
			"# +------------------------------------------------------+ #",
			""),
	WAR_SIEGE_POINTS_SIEGE_BALANCE_CAP_VALUE(
			"war.siege.points_balancing.siege_balance_cap.value",
			"20000",
			"",
			"# This value determines the siege balance cap.",
			"# Set to -1 to disable the cap.",
			"# The value applies to both positive and negative balances e.g. 20000 means a lower limit of -20000 and an upper limit of 20000.",
			"# TIP: Set this value HIGH to give advantage to big nations, and LOW to give advantage to small nations."),
    WAR_SIEGE_POINTS_BALANCING_END_OF_BATTLE_POINTS_DISTRIBUTION(
			"war.siege.points_balancing.end_of_battle_points_distribution",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |         End-Of-Battle Point Distribution             | #",
			"# +------------------------------------------------------+ #",
			""),
	WAR_SIEGE_POINTS_BALANCING_END_OF_BATTLE_POINTS_DISTRIBUTION_WINNER_TAKES_ALL(
			"war.siege.points_balancing.end_of_battle_points_distribution.winner_takes_all",
			"false",
			"",
			"# If true, at the end of a battle, only the battle points of the winner are applied to the siege balance.",
			"# If false, the battle points of the losing side are also applied to the siege balance."),
	/*
	    TODO - Re-enable when end-of-session rollbacks are implemented.

	WAR_SIEGE_WALL_BREACHING(
			"war.siege.wall_breaching",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Wall Breaching                     | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_WALL_BREACHING_ENABLED(
			"war.siege.wall_breaching.enabled",
			"false",
			"",
			"# If true, then the wall breaching feature is enabled.",
			"# If false, then the wall breaching feature is disabled.",
			"# TIP: This feature is disabled by default, to allow servers owners to configure the feature carefully before enabling."),
	WAR_SIEGE_WALL_BREACHING_BREACH_POINT_GENERATION(
			"war.siege.wall_breaching.breach_point_generation",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |               Breach Point Generation                | #",
			"# +------------------------------------------------------+ #",
			""),
	WAR_SIEGE_WALL_BREACHING_BREACH_POINT_GENERATION_RATE(
			"war.siege.wall_breaching.breach_point_generation.rate",
			"0.01",
			"",
			"# This value determines the generation rate of Breach Points from Banner Control.",
			"# Breach Points are automatically generated every SW tick (20 secs) while the town-friendly side has banner control",
			"# Breach points go into a pool which is shared by the whole town-hostile team.",
			"# ---", 
			"# Actual Breach Points = This-Rate x BC-List-Size x Num-Townblocks.",
			"# ---",
			"# TIP: Set this value high enough to allow for fun wall breaching,",
			"# but low enough to prevent excessive griefing of besieged towns."),
	WAR_SIEGE_WALL_BREACHING_BREACH_POINT_GENERATION_MAX_POOL_SIZE(
			"war.siege.wall_breaching.breach_point_generation.max_pool_size",
			"40",
			"",
			"# This value determines the max size of the breach point pool.",
            "# TIP: This value prevents besiegers doing a last-minute, extensive-breaching, dash to the homeblock."),
	WAR_SIEGE_WALL_BREACHING_PLACING_BLOCKS(
			"war.siege.wall_breaching.placing_blocks",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |                   Placing Blocks                     | #",
			"# +------------------------------------------------------+ #",
			""),
	WAR_SIEGE_WALL_BREACHING_PLACING_BLOCKS_COST_PER_BLOCK(
			"war.siege.wall_breaching.placing_blocks.cost_per_block",
			"5",
			"",
			"# This value determines the cost, in Breach Points, to place a block in the besieged town."),			
	WAR_SIEGE_WALL_BREACHING_PLACING_BLOCKS_WHITELIST(
			"war.siege.wall_breaching.placing_blocks.whitelist",
			"endswith=PLANKS, LADDER",
			"",
			"# This list determines the blocks which can be placed by spending Breach Points.",
			"# Supported Special Entries: 'endswith=Partial Material Name'.",
			"# TIP: The default is 'endswith=PLANKS, LADDER' because having only wooden placements allows for easier post-siege cleanup."),			
	WAR_SIEGE_WALL_BREACHING_DESTROYING_BLOCKS(
			"war.siege.wall_breaching.destroying_blocks",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |                  Destroying Blocks                    | #",
			"# +------------------------------------------------------+ #",
			""),
	WAR_SIEGE_WALL_BREACHING_DESTROYING_BLOCKS_COST_PER_BLOCK(
			"war.siege.wall_breaching.destroying_blocks.cost_per_block",
			"12",
			"",
			"# This value determines the cost, in Breach Points, to destroy a block via mining in the besieged town."),			
	WAR_SIEGE_WALL_BREACHING_DESTROYING_BLOCKS_BLACKLIST(
			"war.siege.wall_breaching.destroying_blocks.blacklist",
			"is=entity, BEACON, CHEST, TRAPPED_CHEST, BARREL, FURNACE, BLAST_FURNACE, HOPPER, DROPPER, DISPENSER, ENDER_CHEST, BREWING_STAND, ARMOR_STAND, SHULKER_BOX, BLACK_SHULKER_BOX, BLUE_SHULKER_BOX, BROWN_SHULKER_BOX, CYAN_SHULKER_BOX, GRAY_SHULKER_BOX, GREEN_SHULKER_BOX, LIGHT_BLUE_SHULKER_BOX, LIGHT_GRAY_SHULKER_BOX, LIME_SHULKER_BOX, MAGENTA_SHULKER_BOX, ORANGE_SHULKER_BOX, PINK_SHULKER_BOX, PURPLE_SHULKER_BOX, RED_SHULKER_BOX, WHITE_SHULKER_BOX, YELLOW_SHULKER_BOX",
			"",
			"# This list determines the blocks which cannot be destroyed by spending Breach Points.",
			"# Supported Special Entries: 'is=entity'."),
	WAR_SIEGE_WALL_BREACHING_HOMEBLOCK_BREACH_HEIGHT_LIMIT(
			"war.siege.wall_breaching.homeblock_breach_height_limits",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |             Homeblock Breach Height Limits           | #",
			"# +------------------------------------------------------+ #",
			""),
	WAR_SIEGE_WALL_BREACHING_HOMEBLOCK_BREACH_HEIGHT_LIMITS_MIN(
			"war.siege.wall_breaching.homeblock_breach_height_limits.min",
			"0",
			"",
			"# This setting applies when the block change location is the homeblock, or an adjacent townblock.",
			"# The value is the minimum allowed height at which blocks can be placed/broken via breaching.",
			"# TIP: This feature prevents people excavating bedrock-tunnels straight into the homeblock."),
	WAR_SIEGE_WALL_BREACHING_HOMEBLOCK_BREACH_HEIGHT_LIMITS_MAX(
			"war.siege.wall_breaching.homeblock_breach_height_limits.max",
			"20",
			"",
			"# This setting  applies when the block change location is the homeblock, or an adjacent townblock.",
			"# The value is the maximum allowed height at which blocks can be placed/broken via breaching.",
			"# TIP: This feature prevents people building sky-ramps straight into the homeblock."),
	WAR_SIEGE_WALL_BREACHING_CANNONS_INTEGRATION(
			"war.siege.wall_breaching.cannons_integration",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |                  Cannons Integration                 | #",
			"# +------------------------------------------------------+ #",
			""),
	WAR_SIEGE_WALL_BREACHING_CANNONS_INTEGRATION_ENABLED(
			"war.siege.wall_breaching.cannons_integration.enabled",
			"true",
			"",
			"# If this value is true, all of the configs in this section apply.",
			"# If this value is false, none of the configs in this section apply."),
	WAR_SIEGE_WALL_BREACHING_CANNONS_INTEGRATION_BREACH_POINT_GENERATION_RATE_FROM_CANNON_FIRE(
			"war.siege.wall_breaching.cannons_integration.breach_point_generation_rate_from_cannon_fire",
			"0.07",
			"",
			"# This value determines the generation rate of Breach Points from a single cannon firing.",
			"# ---", 
			"# Actual Breach Points = This-Rate x Num-Townblocks.",
			"# ---",
			"# TIP: Set this value high enough to allow for fun wall breaching,",
			"# but low enough to prevent excessive griefing of besieged towns."),			
	WAR_SIEGE_WALL_BREACHING_CANNONS_INTEGRATION_EXPLODING_BLOCKS_COST_PER_BLOCK(
			"war.siege.wall_breaching.cannons_integration.exploding_blocks_cost_per_block",
			"2",
			"",
			"# This value determines the cost, in Breach Points, to destroy a block via cannon fire explosion in the besieged town."),			
	*/
	SIEGE_MATERIAL_RESTRICTIONS(
			"siege_material_restrictions",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |              Siege Material Restrictions             | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	SIEGE_MATERIAL_RESTRICTIONS_WILDERNESS_BLOCK_PLACEMENT_PREVENTION_MATERIALS(
			"siege_material_restrictions.wilderness_block_placement_prevention_materials",
			"obsidian, ice",
			"",
			"# This setting is useful to help prevent extreme siege-zone grief such as obsidian forts.",
			"# The list is used to indicate the list of blocks which cannot be placed in the wilderness area of siegezones.",
			"# WARNING: Avoid putting 'common' blocks on this list as that may cause lag."),
	SIEGE_MATERIAL_RESTRICTIONS_WILDERNESS_BUCKET_EMPTYING_PREVENTION_MATERIALS(
			"siege_material_restrictions.wilderness_bucket_usage_prevention_materials",
			"lava_bucket, water_bucket, cod_bucket, pufferfish_bucket, salmon_bucket, tropical_fish_bucket, axolotl_bucket",
			"",
			"# This setting is useful to help prevent extreme siege-zone grief such as obsidian forts or cobble monsters.",
			"# The list is used to indicate the list of forbidden buckets"),
	SIEGE_MATERIAL_RESTRICTIONS_WILDERNESS_EXPLOSION_PREVENTION_ENTITY_TYPES(
			"siege_material_restrictions.wilderness_explosion_prevention_entity_types",
			"primed_tnt, minecart_tnt",
			"",
			"# This setting is useful to prevent the dropping of explosive tnt and tnt-minecarts onto the timed-point-zone.",
			"# This setting is used to indicate the list of entity types which will not explode in the wilderness area of siegezones"),
	WAR_SIEGE_DEATH_SPAWN_FIREWORK(
			"war.siege.death.spawn_firework",
			"true",
			"",
			"# If enabled, a firework will get spawned whenever a player dies inside a siege zone."),
	PEACEFUL_TOWNS(
			"neutral_towns",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Neutral Towns                      | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	PEACEFUL_TOWNS_ENABLED(
			"neutral_towns.enabled",
			"true",
			"",
			"# If this is true, then a town can toggle neutrality using /t toggle neutral,",
			"# ",
			"# By activating neutrality, a town voluntarily gives up all official claims to power over a territory,",
			"# in exchange for complete immunity from attack.",
			"# ",
			"# EFFECTS:",
			"# - Town is immune to siege attack (but not to SiegeZone-forced-PVP from nearby sieges).",
			"# - Residents cannot get nation military ranks.",
			"# - Residents get 'war nausea' if they enter siege zones.",
            "# - Town may get automatically peacefully occupied without a siege.",
			"#   (see user guide for full details)",
			"#"),
	PEACEFUL_CAPITALS_ENABLED(
			"neutral_towns.nation_capital_can_be_neutral",
			"false",
			"",
			"# If this is true, a nation capital can be a neutral town. If false, any capital will not be able to turn peaceful."),
	PEACEFUL_TOWNS_CONFIRMATION_REQUIREMENT_DAYS(
			"neutral_towns.confirmation_requirement_days",
			"5",
			"",
			"# This value determines how long it takes to confirm a town neutrality status change.",
			"# It is recommended to be high, for use by genuinely neutral towns, not just for war cost avoidance."),
	PEACEFUL_TOWNS_NEW_TOWN_CONFIRMATION_REQUIREMENT_DAYS(
			"neutral_towns.new_town_confirmation_requirement_days",
			"2",
			"",
			"# This setting applies only in the first week after a town is founded.",
			"# The value determines the countdown duration to be applied to any neutrality switch."),
	PEACEFUL_TOWNS_SUBVERT_ENABLED(
			"neutral_towns.subvert_enabled",
			"true",
			"",
			"# If this setting is true, then peaceful subversion (instant occupation) of neutral towns is enabled."),
	PEACEFUL_TOWNS_PEACEFUL_REVOLT_ENABLED(
			"neutral_towns.revolt_enabled",
			"true",
			"",
			"# If this setting is true, then peaceful revolt (instant de-occupation) by neutral towns is enabled."),
	PEACEFUL_TOWNS_TOWNY_INFLUENCE_RADIUS(
			"neutral_towns.towny_influence_radius",
			"1200",
			"",
			"# This setting describes a circular area surrounding each neutral town.",
			"# The neutral town feels the effect of all 'Towny-Influence' in that area.",
			"# Each nearby automatically generates Towny-Influence in its non-neutral, non-sieged towns in the area. The value is measured in num-townblocks.",
			"# The nation with the highest Towny-Influence can subvert (peacefully occupy) the neutral town, if it wishes to do so."),
	PEACEFUL_TOWNS_SICKNESS_WARNING_DURATION_SECONDS(
			"neutral_towns.sickness_warning_duration_seconds",
			"20",
			"",
			"# This value determines the number of warning seconds before war allergy (sickness) applies."),
	OCCUPIED_TOWNS(
			"occupied_towns",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Occupied Towns                     | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	OCCUPIED_TOWN_UNCLAIMING_DISABLED(
			"occupied_towns.occupied_town_unclaiming_disabled",
			"true",
			"",
			"# If this value is true, then a town under occupation cannot unclaim.",
			"#  This setting is recommended, to avoid occupation escape exploits."),
	OCCUPIED_TOWN_CORRECT_CONQUERED_STATUS(
			"occupied_towns.automatically_remove_conquered_status_when_unable_to_load_nation",
			"true",
			"",
			"# Leave this setting to true. Only used under very specific circumstances for which you will be given instructions personally."),
	
	PUNISH_NON_SIEGE_PARTICIPANTS_IN_SIEGE_ZONE(
			"punish_non_siege_participants_in_siege_zones",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |        Punishing unofficial siege participants       | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	ENABLE_SICKNESS(
			"punish_non_siege_participants_in_siege_zones.enable_sickness",
			"true",
			"",
			"# If true, players that are not participating in a siege will receive war sickness",
			"# A non-participant is a player who does not have a military rank, is not allied to either the attacker or the defender, or is neutral.",
			"# There are two types of war sickness, full and special.",
			"# Special war sickness is only given if a non-participant is at his town that happened to be in a siege zone",
			"#   - Effects: Weakness V",
			"# Full sickness is given to all players that are not allied to either side, do not have a military rank, or is neutral, and are not in their own town.",
			"#   - Effects: Health 1, Nausea V, Poison V, Weakness V, Slowness III, Mining Fatigue III"
	),
	SECONDS_BEFORE_SICKNESS(
			"punish_non_siege_participants_in_siege_zones.seconds_warning",
			"20",
			"",
			"# This is how many seconds a player has to leave the siege zone before he gets war sickness",
			"# If this is set to 0, no warn will be given and non-participants will receive war sickness instantly, if enabled"
	),
	BEACON_MARKERS(
			"beacon_markers",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Beacon Markers                     | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	BEACON_MARKERS_ENABLED(
			"beacon_markers.enabled",
			"true",
			"",
			"# If enabled, client-side beacons will be shown for players at the siege banner while they are in a siege zone."),
	BEACON_MARKERS_CAPTURE_COLOR(
			"beacon_markers.capture_color",
			"yellow",
			"",
			"# The color that the beacon will be while a player is capturing it. Only visible to the player.",
			"# Accepts any of the following colors (case insensitive): White, Orange, Magenta, LightBlue, Yellow, Lime, Pink, Gray, LightGray, Cyan, Purple, Blue, Brown, Green, Red & Black.",
			"# Defaults to yellow if no valid color is entered."),
	BEACON_MARKERS_CAPTURED_COLOR(
			"beacon_markers.captured_color",
			"green",
			"",
			"# The color that the beacon will be for a player when their side has control of the banner.",
			"# See above for valid colors.",
			"# Defaults to green if no valid color is entered."),
	BEACON_MARKERS_ENEMY_COLOR(
			"beacon_markers.enemy_color",
			"red",
			"",
			"# The color that the beacon will be for a player when the enemy side has control of the banner.",
			"# See above for valid colors.",
			"# Defaults to red if no valid color is entered."),
	BANNER_XYZ_TEXT(
			"banner_xyz_text",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Banner XYZ Text                    | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	BANNER_XYZ_TEXT_ENABLED(
			"banner_xyz_text.enabled",
			"false",
			"# The banner xyz text is an alternative to beacon markers for siege banners (but they can also be used together).",
			"# If enabled, besieged towns will show the XYZ of the siege banner on their town screens."),
	NATION_SIEGE_IMMUNITY(
		"nation_siege_immunity",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                 Nation Siege Immunity                | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	NATION_SIEGE_IMMUNITY_ENABLED(
			"nation_siege_immunity.enabled",
			"false",
			"",
			"# If this setting is true, then nation siege immunity is enabled.",
			"# ",
			"# This feature gives each nation regular breaks from war, ",
			"# by granting siege-immunity to all their towns after a home-defence war.",
			"# ",
			"# A home-defence war is a period in which one or more of a nation's towns are under siege.",
			"# ",
			"# NOTES:",
			"# 1. To mitigate exploits, nations suffer some mild negative effects while fighting a home-defence war - cannot claim/unclaim/recruit.",
			"# 2. To mitigate annoyance-sieges, the cost to attack a nation's towns increases as that nation increases in size.",
			"# 3. If a town switches nation during a home-defence war",
			"#     then when the home-defence war ends, the post-war immunity from that town,",
			"#     is distributed between all the nations which the town had during the siege",
			"#     (but not any occupying nation)."),
	NATION_SIEGE_IMMUNITY_DURATION_MODIFIER(
			"nation_siege_immunity.duration_modifier",
			"0.5",
			"",
			"# This setting determines the duration of siege immunity which each nation town receives after a home defence war.",
			"# ",
			"# FORMULA:",
			"# Nation-Town Immunity Duration = Total Duration of Sieges x This Value.",
			"# ",
			"# EXAMPLE:",
			"# A nation suffers a big home defence war, of 4 sieges, with each siege lasting 3 days.",
			"# This gives a Total Siege Duration of 12 days",
			"# If this value is 0.5, then immunity duration will be 6 days",
			"# Thus when the war ends, each non-besieged nation town will get 6 days of siege immunity."),
	NATION_SIEGE_IMMUNITY_HOME_TOWN_CONTRIBUTION_TO_ATTACK_COST(
			"nation_siege_immunity.home_town_contribution_to_attack_cost",
			"0.1",
			"",
			"# If this setting is higher than 0,",
			"# then the larger a nation is, the higher the cost to attack one of its towns.",
			"# ",
			"# This setting is important to mitigate 'annoyance sieges', ",
			"# because large nations are disproportionately affected by the mild home defence war restrictions.",
			"# Thus without mitigation, small nations could attack larger ones,",
			"# with no intention of fighting, but just to cheaply disrupt them.",
			"# ",
			"# EXAMPLE:",
			"# If this setting is 0.1,",
			"# and an attack is attempted on a nation town,",
			"# then for every natural town (i.e. not occupied foreign towns) in that nation,",
			"# the attack-cost (i.e. warchest) requirement is increased by 10% of the amount it would take to attack that town."),
	BANNER_CONTROL(
		"banner_control",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                    BANNER CONTROL                    | #",
			"# +------------------------------------------------------+ #",
			"#                                                          #",
			"# FYI: Most banner-control-related settings are above,     #",
			"# and not in this section.                                 #",
			"############################################################",
			""),
	BANNER_CONTROL_CAPTURE_MESSAGE_COLOR(
			"banner_control.capturing_message_color",
			"yellow",
			"",
			"# This setting determines the color of the boss bar message,",
			"# which players see while they are capturing the banner."),
	SIEGE_START_DAY_LIMITER(
		"siege_start_day_limiter",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |              SIEGE START DAY LIMITER                 | #",
			"# +------------------------------------------------------+ #",
			"#                                                          #",
			"# The feature allows a server to limit the days when       #",
			"# players can start sieges.                                #",
			"# 						                                    #",
			"# Example: If you wanted fighting mostly on the weekends   #",
			"# you could limit siege-starts to just Friday.             #",
			"############################################################",
			""),
	SIEGE_START_DAY_LIMITER_ALLOWED_DAYS(
			"siege_start_day_limiter.allowed_days",
			"monday, tuesday, wednesday, thursday, friday, saturday, sunday",
			"",
			"# This setting determines the days (in server timezone) when players can start sieges.",
			"# Multiple entries should be separated by a comma.",
			"# Permitted values: monday, tuesday, wednesday, thursday, friday, saturday, sunday."),
    BATTLE_SESSION_SCHEDULER(
			"battle_session_scheduler",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |               Battle Session Scheduler               | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
    BATTLE_SESSION_SCHEDULER_START_TIMES(
			"battle_session_scheduler.start_times",
			"",
			"",
			"# TIP: Do not rely only on the Battle Session Scheduler to prevent no-life-sieging.",
			"# Try to also make use of the capping limiter for that purpose"),
	BATTLE_SESSION_SCHEDULER_START_TIMES_WEEKDAYS(
			"battle_session_scheduler.start_times.weekdays",
			"00:10,01:10,02:10,03:10,04:10,05:10,06:10,07:10,08:10,09:10,10:10,11:10,12:10,13:10,14:10,15:10,16:10,17:10,18:10,19:10,20:10,21:10,22:10,23:10",
			"",
			"# This value determines the weekday times (in Server timezone) when each battle session will start.",
			"# This setting applies to Monday, Tuesday, Wednesday, Thursday, and Friday.",
			"# The format is HOUR:MINUTE.",
			"# The default values are all at ten past the hour, so that the critical point of the battle (the final minutes), will fall on the hour."),
	BATTLE_SESSION_SCHEDULER_START_TIMES_WEEKEND_DAYS(
			"battle_session_scheduler.start_times.weekend_days",
			"00:10,01:10,02:10,03:10,04:10,05:10,06:10,07:10,08:10,09:10,10:10,11:10,12:10,13:10,14:10,15:10,16:10,17:10,18:10,19:10,20:10,21:10,22:10,23:10",
			"",
			"# This value determines the weekend times (in Server timezone) when each battle session will start.",
			"# This setting applies to Saturday and Sunday.",
			"# The format is HOUR:MINUTE.",
			"# The default values are all at ten past the hour, so that the critical point of the battle (the final minutes), will fall on the hour."),
	BATTLE_SESSION_SCHEDULER_DURATION_MINUTES(
			"battle_session_scheduler.duration_minutes",
			"50",
			"",
			"# This value determines the duration of each battle session.",
			"# TIP: The default value of 50 is deliberately designed to give players a 10 minute break after each battle session, for reasons of health and safety."),
	BATTLE_SESSION_SCHEDULER_CANCEL_SESSION_WHEN_NO_SIEGES(
			"battle_session_scheduler.cancel_session_when_no_active_sieges",
			"true",
			"",
			"# Should sessions be cancelled when there are no active sieges?"),
	CAPPING_LIMITER(
			"capping_limiter",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                    Capping Limiter                     #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	CAPPING_LIMITER_WEEKDAY_BATTLE_SESSIONS(
			"capping_limiter.weekday_battle_sessions",
			"3",
			"",
			"# This value determines the maximum number of week-day battle sessions which each player can cap at.",
			"# To disable the feature, set the value to -1.",
			"# TIP: This feature helps to prevent teams trying to win by fight-avoidance with capping."),
	CAPPING_LIMITER_WEEKEND_DAY_BATTLE_SESSIONS(
			"capping_limiter.weekend_day_battle_sessions",
			"6",
			"",
			"# This value determines the maximum number of weekend-day battle sessions which each player can at.",
			"# To disable the feature, set the value to -1.",
			"# TIP: This feature helps to prevent teams trying to win by fight-avoidance with capping."),
	PVP_PROTECTION_OVERRIDES(
			"pvp_protection_overrides",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |               PVP Protection Overrides               | #",
			"# +------------------------------------------------------+ #",
			"#                                                          #",
			"# Other plugins, including Towny, can protect players      #",
			"# from PVP, even when those players are in Siege-Zones.    #",
			"# 						            #",
			"# This section allows server owners to override those      #",
			"# protections, and stop them from working in Siege-Zones.  #",
			"############################################################",
			""),
	PVP_PROTECTION_OVERRIDES_STOP_TOWNY_PLOT_PVP_PROTECTION(
			"pvp_protection_overrides.stop_towny_plot_protection",
			"true",
			"",
			"# If true, then Towny plot protection is disabled in Siege-Zones.",
			"# TIP: This value is generally set to true, to avoid having unnatural safe claims within Siege-Zones."),
	PVP_PROTECTION_OVERRIDES_STOP_TOWNY_FRIENDLY_FIRE_PROTECTION(
			"pvp_protection_overrides.stop_towny_friendly_fire_protection",
			"false",
			"",
			"# If true, then Towny friendly-fire protection is disabled within Siege-Zones."),
	PVP_PROTECTION_OVERRIDES_STOP_ALL_PVP_PROTECTION(
			"pvp_protection_overrides.stop_all_protection",
			"false",
			"",
			"# If true, then all PVP protections are disabled within Siege-Zones, including from non-TownyAdvanced plugins.",
			"# WARNING : This setting may result in incorrect pvp-protection messaging information!."),
	TRAP_WARFARE_MITIGATION(
			"trap_warfare_mitigation",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |               TRAP WARFARE MITIGATION                | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	TRAP_WARFARE_MITIGATION_ENABLED(
			"trap_warfare_mitigation.enabled",
			"true",
			"",
			"# If this setting is true, then players cannot build/destroy blocks in a certain area near the Siege Banner.",
			"# ",
			"# TIP: ",
			"# If this feature is enabled, ",
			"# then it is recommended to also have a server rule requiring attackers to remove all traps in the area before the banner is placed"),
	TRAP_WARFARE_MITIGATION_RADIUS_BLOCKS(
			"trap_warfare_mitigation.radius_blocks",
			"32",
			"",
			"# The radius of block protection around the Siege Banner"),
	TRAP_WARFARE_MITIGATION_UPPER_HEIGHT_LIMIT(
			"trap_warfare_mitigation.upper_height_limit",
			"10",
			"",
			"# Within the protection radius, players cannot build above this height.",
			"# The height is relative to the siege banner height"),
	TRAP_WARFARE_MITIGATION_LOWER_HEIGHT_LIMIT(
			"trap_warfare_mitigation.lower_height_limit",
			"0",
			"",
			"# Within the protection radius, players cannot build below this height.",
			"# The height is relative to the siege banner height"),
	DOMINATION_AWARDS(
			"domination_awards",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                  DOMINATION AWARDS                   | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS(
			"domination_awards.artefact_offers",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |                    Artefact Offers                   | #",
			"# +------------------------------------------------------+ #",
			"",
			"# These offers determine which artefacts are available for granting.",
			"# ",
			"# OVERALL SECTIONS",
			"# There are 2 overall sections:",
			"# - Default: Do not modify. Provided by the plugin. If there are any issues with these, report to plugin team.",
			"# - Custom: You can add new artefacts here.",
			"# ",
			"# ARTEFACT SECTIONS",
			"# Each artefact offer has 3+ sections:",
			"# Section 1 - key      ..... this key must be unique.",
			"# Section 2 - quantity ..... the number of artefacts in the offer.",
			"# Section 3 - material ..... the material the artefacts are made of.",
			"# Section 4 - [OPTIONAL] effect 1 ...... A Special effect. There are 3 format options. See below.",
			"# Section 5 - [OPTIONAL] effect 2 ...... A Special effect.  A new section can be added for each additional effects.",
			"# ",
			"# SPECIAL EFFECT FORMAT OPTIONS",
			"# Option 1:  For tools/weapons/armour:  <effect_type>:<amplifier>",
			"# Option 2:  For potions/arrows:   <potion_type>:<amplifier>:<duration_seconds>:<particles>:<ambient>:<icon>",
			"# Option 3:  For custom effects:     custom_effect:<custom_effect_key>",
			"# ",
			"# NOTES",
			"# 1. For all artefacts, the name must appear in the language file.",
			"# 2. For custom effects, an effect description must also appear in the language file.",
			"# ",
			"# +------------------------------------------------------+ #",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_DEFAULT(
			"domination_awards.artefact_offers.default_0_8_0_official",
			"",
			"# These artefacts are the defaults provided by SW. Do not add custom items here."),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_DEFAULT_TIER1(
			"domination_awards.artefact_offers.default_0_8_0_official.tier1",
			"{cobble_eater, 1, diamond_pickaxe, efficiency:7}"
			+ "{tree_feller, 1, diamond_axe, efficiency:7}"
			+ "{ground_digger, 1, diamond_shovel, efficiency:7}"
			+ "{sword_of_searing, 1, golden_sword, fire_aspect:4}"
			+ "{poison_blade, 1, golden_sword, custom_effect:poison_on_hit}"
			+ "{potion_of_enhanced_regeneration, 3, potion, regeneration:3:60:true:true:true}"
			+ "{potion_of_enhanced_strength, 3, potion, increase_damage:3:120:true:true:true}"
			+ "{potion_of_enhanced_absorbtion, 3, potion, absorption:3:120:true:true:true}",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_DEFAULT_TIER2(
			"domination_awards.artefact_offers.default_0_8_0_official.tier2",
			"{potion_of_true_invisibility, 3, potion, invisibility:1:180:false:false:true}"
			+ "{splash_potion_of_enhanced_regeneration, 3, splash_potion, regeneration:3:60:true:true:true}"
			+ "{splash_potion_of_enhanced_strength, 3, splash_potion, increase_damage:3:120:true:true:true}"
			+ "{splash_potion_of_enhanced_absorbtion, 3, splash_potion, absorption:3:120:true:true:true}",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_DEFAULT_TIER3(
			"domination_awards.artefact_offers.default_0_8_0_official.tier3",
			"{arrow_of_enhanced_hunger, 5, tipped_arrow, hunger:12:50:true:true:true}"
			+ "{potion_of_great_resistance, 3, potion, damage_resistance:4:30:true:true:true}"
			+ "{splash_potion_of_true_invisibility, 3, splash_potion, invisibility:1:180:false:false:true}"
			+ "{arrow_of_knockup, 5, tipped_arrow, levitation:20:1:true:true:true}"
			+ "{super_spiky_helmet, 1, golden_helmet, thorns:8, unbreaking:2}"
			+ "{bountiful_pickaxe, 1, diamond_pickaxe, fortune:5, efficiency:8}",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_DEFAULT_TIER4(
			"domination_awards.artefact_offers.default_0_8_0_official.tier4",
			"{sword_of_immolation, 1, golden_sword, fire_aspect:7}"
			+ "{axe_of_the_berserker, 1, golden_axe, sharpness:10, efficiency:10}"
			+ "{bow_of_displacement, 1, bow, punch: 7}"
			+ "{blade_of_the_viper, 1, golden_sword, custom_effect:strong_poison_on_hit, custom_effect:slow_on_hit}",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_DEFAULT_TIER5(
			"domination_awards.artefact_offers.default_0_8_0_official.tier5",
			"{arrow_of_doom, 5, tipped_arrow, harm:20:1:true:true:true}"
			+ "{vorpal_sword, 1, golden_sword, sharpness:15}"
			+ "{chicago_typewriter, 1, crossbow, quick_charge:5}"
			+ "{trident_of_zeus, 1, trident, channeling:1, loyalty:2, custom_effect:lightning_strike_on_hit}"
			+ "{trident_of_poseidon, 1, trident, riptide:12}"
			+ "{chestplate_of_mars, 1, golden_chestplate, protection:10}"
			+ "{antimatter_potion, 1, potion, poison:1:7:true:true:true, custom_effect:delayed_massive_self_explosion_on_consume}",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_CUSTOM(
			"domination_awards.artefact_offers.custom",
			"",
			"# These artefacts are configured by the server. You can add custom items here."),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_CUSTOM_TIER1(
			"domination_awards.artefact_offers.custom.tier1",
			"",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_CUSTOM_TIER2(
			"domination_awards.artefact_offers.custom.tier2",
			"",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_CUSTOM_TIER3(
			"domination_awards.artefact_offers.custom.tier3",
			"",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_CUSTOM_TIER4(
			"domination_awards.artefact_offers.custom.tier4",
			"",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_CUSTOM_TIER5(
			"domination_awards.artefact_offers.custom.tier5",
			"",
			""),
	DOMINATION_AWARDS_ARTEFACT_OFFERS_LEGACY(
			"domination_awards.artefact_offers.legacy",
			"",
			"",
			"# This list is inactive. The artefacts here will not be offered.",
			"# This list exists only to preserve any custom artefacts which users added in 0.7.15.",
			"# To offer these artefacts, move them into the custom offers configs above."),
	DOMINATION_AWARDS_ARTEFACT_CHEST_SIGNS(
			"domination_awards.artefact_chest_signs",
			"artefacts, artifacts",
			"",
			"# When a nation is granted artefacts. the items get placed in chests in the capital homeblock.",
			"# If the nation puts a sign on any chests with one of these texts, those chests will be preferred."),
	DOMINATION_AWARDS_ARTEFACT_EXPIRY(
			"domination_awards.artefact_expiry",
			"",
			"",
			"",
			"# +------------------------------------------------------+ #",
			"# |                    Artefact Expiry                   | #",
			"# +------------------------------------------------------+ #",
			""),
	DOMINATION_AWARDS_ARTEFACT_EXPIRY_LIFETIME_DAYS(
			"domination_awards.artefact_expiry.lifetime_days",
			"7",
			"",
			"# The lifetime in days of each artefact."),
	DOMINATION_AWARDS_ARTEFACT_EXPIRY_PERCENTAGE_CHANCE_PER_SHORT_TICK(
			"domination_awards.artefact_expiry.percentage_chance_per_short_tick",
			"10",
			"",
			"# The percentage chance per short tick, that all end-of-life artefacts within a player's inventory will expire.",
			"# TIP: Keep this value low to avoid lag."),
	DOMINATION_AWARDS_ARTEFACT_EXPIRY_EXPLOSIONS(
			"domination_awards.artefact_expiry.explosions",
			"",
			""),
	DOMINATION_AWARDS_ARTEFACT_EXPIRY_EXPLOSIONS_ENABLED(
			"domination_awards.artefact_expiry.explosions.enabled",
			"true",
			"",
			"# If true, an artefact will explode on expiration."),
	DOMINATION_AWARDS_ARTEFACT_EXPIRY_EXPLOSIONS_BASE_POWER(
			"domination_awards.artefact_expiry.explosions.base_power",
			"4",
			"",
			"# The base power of the explosion."),
	DOMINATION_AWARDS_ARTEFACT_EXPIRY_EXPLOSIONS_EXTRA_POWER_PER_EXPIRED_ARTEFACT(
			"domination_awards.artefact_expiry.explosions.extra_power_per_expired_artefact",
			"1",
			"",
			"# The explosion power increases with every expired artefact the player is carrying."),
	DOMINATION_AWARDS_ARTEFACT_EXPIRY_EXPLOSIONS_MAX_POWER(
			"domination_awards.artefact_expiry.explosions.max_power",
			"9",
			"",
			"# The max power of the explosion."),
	DOMINATION_AWARDS_GLOBAL(
			"domination_awards.global",
			"",
			""),
	DOMINATION_AWARDS_GLOBAL_ENABLED(
			"domination_awards.global.enabled",
			"true",
			"",
			"# If this setting is true, then global domination awards are enabled."),
	DOMINATION_AWARDS_GLOBAL_MINIMUM_ASSESSMENT_CRITERION(
			"domination_awards.global.assessment_criterion",
			"num_residents",
			"",
			"# The criterion by which the award winners are chosen.",
			"# Allowed values: num_residents, num_towns, num_townblocks, num_online_players"),
	DOMINATION_AWARDS_GLOBAL_MINIMUM_ASSESSMENT_PERIOD_HOURS(
			"domination_awards.global.assessment_period_hours",
			"150",
			"",
			"# The minimum assessment period required before awards are granted."),
	DOMINATION_AWARDS_GLOBAL_GRANT_DAY_OF_WEEK(
			"domination_awards.global.grant_day_of_week",
			"Saturday",
			"",
			"# The day on which the award is granted. It will be granted on Towny New Day."),
	DOMINATION_AWARDS_GLOBAL_GRANTED_MONEY(
			"domination_awards.global.granted_money",
			"2000,1500,1250,1000,750,500,250",
			"",
			"# The money granted by the awards.",
			"# This list is in the form of: top_nation, next nation,......bottom_nation"),
	DOMINATION_AWARDS_GLOBAL_GRANTED_ARTEFACT_OFFERS(
			"domination_awards.global.granted_artefact_offers",
			"{8,7,5,3,2} {7,6,4,2,1} {6,5,3,1,0} {5,4,2,0,0} {4,3,1,0,0} {3,2,0,0,0} {2,1,0,0,0}",
			"",
			"# The offers granted by the awards.",
			"# This list is in the form of: {top_nation}, {next nation},......{bottom_nation}",
			"# Within each nation, the form is: {num_tier_1_offers, num_tier_2_offers .....}. etc.");

	private final String Root;
	private final String Default;
	private String[] comments;

	ConfigNodes(String root, String def, String... comments) {

		this.Root = root;
		this.Default = def;
		this.comments = comments;
	}

	/**
	 * Retrieves the root for a config option
	 *
	 * @return The root for a config option
	 */
	public String getRoot() {

		return Root;
	}

	/**
	 * Retrieves the default value for a config path
	 *
	 * @return The default value for a config path
	 */
	public String getDefault() {

		return Default;
	}

	/**
	 * Retrieves the comment for a config path
	 *
	 * @return The comments for a config path
	 */
	public String[] getComments() {

		if (comments != null) {
			return comments;
		}

		String[] comments = new String[1];
		comments[0] = "";
		return comments;
	}

}
