package com.gmail.goosius.siegewar.settings;

public enum ConfigNodes {

	VERSION_HEADER("version", "", ""),
	VERSION(
			"version.version",
			"",
			"# This is the current version.  Please do not edit."),
	LAST_RUN_VERSION(
			"version.last_run_version",
			"",
			"# This is for showing the changelog on updates.  Please do not edit."),
	LANGUAGE(
			"language",
			"english.yml",
			"# The language file you wish to use"),
	WAR("war","","",""),
	WAR_SIEGE(
			"war.siege",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Siege-War settings                 | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_SWITCHES(
			"war.siege.switches",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                       Switches                       | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_ENABLED(
			"war.siege.switches.enabled",
			"true",
			"",
			"# If true, the Siege-War system is enabled.",
			"# if false, the Siege-War system is disabled."),
	WAR_SIEGE_CONQUEST_SIEGES_ENABLED(
			"war.siege.switches.conquest_sieges_enabled",
			"true",
			"",
			"# If true, then nations can start conquest sieges."),
	WAR_SIEGE_LIBERATION_SIEGES_ENABLED(
			"war.siege.switches.liberation_sieges_enabled",
			"true",
			"",
			"# If true, then nations can start liberation sieges."),
	WAR_SIEGE_REVOLT_SIEGES_ENABLED(
			"war.siege.switches.revolt_sieges_enabled",
			"true",
			"",
			"# If true, then towns can start revolt sieges."),
	WAR_SIEGE_SUPPRESSION_SIEGES_ENABLED(
			"war.siege.switches.suppression_sieges_enabled",
			"true",
			"",
			"# If true, then nations can start suppression sieges."),
	WAR_SIEGE_ABANDON_ENABLED(
			"war.siege.switches.abandon_enabled",
			"true",
			"",
			"# If true, then attackers can abandon sieges."),
	WAR_SIEGE_SURRENDER_ENABLED(
			"war.siege.switches.town_surrender_enabled",
			"true",
			"",
			"# If true, then defenders can surrender sieges."),
	WAR_SIEGE_INVADE_ENABLED(
			"war.siege.switches.invade_enabled",
			"true",
			"",
			"# If true, then invasions are enabled."),
	WAR_SIEGE_PLUNDER_ENABLED(
			"war.siege.switches.plunder_enabled",
			"true",
			"",
			"# If true, then plunder is enabled.",
			"# This action will steal money from the town, and transfer it to the victorious nation.",
			"# The below setting of war.siege.money.attacker_plunder_distribution_ratio determines the nation-bank/soldiers distribution",
			"# If the town does not have sufficient funds, it will be bankrupted/ruined/destroyed."),
	WAR_SIEGE_MILITARY_SALARY_ENABLED(
			"war.siege.switches.military_salary_enabled",
			"true",
			"",
			"# If true, then a king can pay their soldiers using '/sw nation paysoldiers <total amount>'.",
			"# The amount will be distributed among the soldiers according to their ranks.",
			"# The permission of siegewar.nation.siege.pay.grade.x, determines how much a rank is paid. x=100 is a normal share, x=200 is double"),
	WAR_SIEGE_PVP_ALWAYS_ON_IN_BESIEGED_TOWNS(
			"war.siege.switches.pvp_always_on_in_besieged_towns",
			"true",
			"",
			"# If true, then town pvp is always set to on during sieges.",
			"# The town pvp flag returns to its previous value when the siege ends."),
	WAR_SIEGE_CLAIMING_DISABLED_NEAR_SIEGE_ZONES(
			"war.siege.switches.claiming_disabled_near_siege_zones",
			"true",
			"",
			"# If true, then land cannot be claimed near a siege zone.",
			"# This setting is generally considered critical, otherwise one side could wall off the siege zone."),
	WAR_SIEGE_NON_RESIDENT_SPAWN_INTO_SIEGE_ZONES_OR_BESIEGED_TOWNS_DISABLED(
			"war.siege.switches.non_resident_spawn_into_siegezones_or_besieged_towns_disabled",
			"true",
			"",
			"# If this setting is true, then only town residents are permitted to spawn into siegezones OR besieged towns.",
			"# This setting is recommended to:",
			"# 1. Protect players from accidentally spawning into a warzone while unprepared.",
			"# 2. Discourage 'fake' sieges, by making the automatic siege impact harsher.",
			"# 3. Even the spawn-advantage between attacking and defender."), 
	WAR_SIEGE_BESIEGED_TOWN_RECRUITMENT_DISABLED(
			"war.siege.switches.besieged_town_recruitment_disabled",
			"true",
			"",
			"# If this value is true, then a town under active siege cannot recruit new residents.",
			"#  This setting is recommended because it helps discourage 'fake' sieges just for the purpose of of gifting immunity."),
	WAR_SIEGE_BESIEGED_TOWN_CLAIMING_DISABLED(
			"war.siege.switches.besieged_town_claiming_disabled",
			"true",
			"",
			"# If this value is true, then a town under active siege cannot claim new plots.",
			"#  This setting is recommended because it helps discourage 'fake' sieges just for the purpose of of gifting immunity."),
	WAR_SIEGE_BESIEGED_TOWN_UNCLAIMING_DISABLED(
			"war.siege.switches.besieged_town_unclaiming_disabled",
			"true",
			"",
			"# If this value is true, then a town under active siege cannot unclaim.",
			"#  This setting is recommended if invasion/occupation is enabled, to avoid occupation escape exploits."),
	WAR_SIEGE_COUNTERATTACK_BOOSTER_ENABLED(
			"war.siege.switches.counterattack_booster_enabled",
			"false",
			"",
			"# This feature is an essential feature for a good server experience, ",
			"# as described in detail in the the online User Guide and FAQ.",
			"#",
			"# If this setting is false, then if a player from the banner controlling side dies,",
			"# the death points are increased by a certain percentage, configured in a separate section.",
			"# ",
			"# WARNING: Do not enable this feature without first reviewing the following config setting: ",
			"# - counterattack_booster_extra_death_points_per_player_percentage"),
	WAR_SIEGE_NATION_STATISTICS_ENABLED(
			"war.siege.switches.nation_statistics_enabled",
			"true",
			"",
			"# If this setting is true, then Siegewar statistics will be shown on nation status screens."),
	WAR_SIEGE_SWITCHES_TRAP_WARFARE_MITIGATION_ENABLED(
			"war.siege.switches.trap_warfare_mitigation_enabled",
			"false",
			"",
			"# If this setting is true, then ",
			"# 1. Players cannot build/destroy blocks in the timed point zone below the siege banner altitude, and",
			"# 2. Banner control cannot be gained if the player is below the siege banner altitude",
			"# NOTE: ",
			"# If you enable this feature, ",
			"# make sure to also have a server rule preventing traps being created in the timed-point-zone BEFORE the banner is placed"),
	WAR_SIEGE_DEATH_PENALTY_KEEP_INVENTORY_ENABLED(
			"war.siege.switches.keep_inventory_on_siege_death",
			"true",
			"",
			"# This is an important feature to support casual players and prevent nations snowballing,",
			"# as described in the online FAQ page.",
			"# ",
			"# If the setting is true then military ranked players keep inventory on siege-zone death.",
			"# See the 'death penalties' section below for more settings in this area"),
	WAR_SIEGE_DEATH_PENALTY_KEEP_LEVEL_ENABLED(
			"war.siege.switches.keep_level_on_siege_death",
			"true",
			"",
			"# This is an important feature to support casual players. ",
			"# ",
			"# If the setting is true then military ranked players keep level on siege-zone death.",
			"# See the 'death penalties' section below for more settings in this area"),
	WAR_SIEGE_MONEY(
			"war.siege.money",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                       Money                          | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_ATTACKER_COST_UPFRONT_PER_PLOT(
			"war.siege.money.attacker_cost_upfront_per_plot",
			"20.0",
			"",
			"# This value represents the siege deposit paid by the attacker",
			"# This is the 'warchest' (a money-account, not an actual chest object).",
			"# If the attacking nation wins the siege, the warchest is returned to the nation bank.",
			"# If the defending town wins the siege, the warchest is recovered by the defenders.",
			"# See below for more details on how the warchest is distributed among the defenders."),
	WAR_SIEGE_ATTACKER_PLUNDER_AMOUNT_PER_PLOT(
			"war.siege.money.attacker_plunder_amount_per_plot",
			"40.0",
			"",
			"# This is the amount which an attacking nation will plunder if they choose to do so after a siege victory.",
			"# See below for more details on how the plunder is distributed."),
	WAR_SIEGE_PLUNDER_DISTRIBUTION_RATIO(
			"war.siege.money.plunder_distribution_ratio",
			"1:3",
			"",
			"# This ratio affects how plunder is distributed among the winning team.",
			"# The value on the left is the ratio which will go to the government bank (town or nation).",
			"# The value on the right is the ratio which will go to the contributing soldiers",
			"# For each battle in which a soldier gained banner control at least once, that soldier receives 1 share.",
			"# The total soldiers' share is distributed accordingly among the army."),
	WAR_SIEGE_CAPITAL_SIEGE_COST_INCREASE_PERCENTAGE(
			"war.siege.money.capital_siege_cost_increase_percentage",
			"0",
			"",
			"# The percentage to increase the cost of sieging capitals by.",
			"# Example: If set to 50, with an attack cost of 20/plot, each plot would be 30."),
	WAR_SIEGE_EXTRA_MONEY_PERCENTAGE_PER_TOWN_LEVEL(
			"war.siege.money.extra_money_percentage_per_town_level",
			"0",
			"",
			"# This value increases the monetary costs & gains of sieges, depending on town level.",
			"# ",
			"# The value is useful to ensure that larger towns/nations will not feel unaffected by war moneys.",
			"# The value is applied to attack cost (war-chest) and plunder.",
			"# The value is appropriate in servers where town wealth does not correspond linearly to number of plots.",
			"# Example: On server x, small towns tend to have 10 plots + 100 gold, and large towns tend to have 100 plots + 999,999 gold.",
			"#          Clearly on this server, wealth is heavily concentrated in larger towns. Thus this value should be high ",
	        "# ",
			"# Example of how this value would affect attack cost (@20/plot), if the value was set to 50 : ",
			"# ",
			"# Level 1 (1 resident), 5 plots. Cost = (20 * 5) + 0% = 100",
			"# Level 2 (3 residents), 15 plots. Cost = (20 * 15) + 50% = 450",
			"# Level 3 (8 residents), 50 plots. Cost = (20 * 50) + 100% = 2000",
			"# Level 4 (12 residents), 80 plots. Cost = (20 * 80) + 150% = 4000",
			"# ",
			"# If the value is 0, then money amounts are not modified."),
	WAR_SIEGE_QUANTITIES(
			"war.siege.quantities",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |              Non-Monetary Quantities                 | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_MAX_ACTIVE_SIEGE_ATTACKS_PER_NATION(
		"war.siege.quantities.max_active_siege_attacks_per_nation",
		"3",
		"",
			"# The value specifies the maximum number of active attack sieges allowed per nation." +
			"# A low setting will generally reduce the aggression level on the server.",
			"# A low setting will also rebalance the system in favour of smaller nations.",
		 	"# This is because it will prevent larger nations from conducting as many sieges as their resources would otherwise allow."),
	WAR_SIEGE_SIEGECAMPS(
	"war.siege.siegecamps",
	"",
	"",
	"",
	"############################################################",
	"# +------------------------------------------------------+ #",
	"# |                    Siege Camps                       | #",
	"# + SiegeCamps precede Sieges, begun when a banner is    | #",
	"# + first placed. By default a 10 minute session in which| #",
	"# + the attacking town must score a given number of      | #",
	"# + points in order to begin a siege. This feature is    | #",
	"# + meant to mitigate towns creating mock-sieges, and    | #",
	"# + using the resulting immunity to avoid sieges by real | #",
	"# + enemies                                              | #",
	"# +------------------------------------------------------+ #",
	"############################################################",
	""),
	WAR_SIEGE_SIEGECAMPS_ENABLED(
			"war.siege.siegecamps.enabled",
			"true",
			"",
			"# When true, SiegeWar will begin each attempted Siege with a SiegeCamp session."),
	WAR_SIEGE_SIEGECAMPS_COOLDOWN(
			"war.siege.siegecamps.failed_siegecamp_cooldown",
			"12h",
			"",
			"# When a town fails a SiegeCamp, how long until they can attempt to SiegeCamp the town again?"),
	WAR_SIEGE_SIEGECAMPS_POINTS(
			"war.siege.siegecamps.points_required_to_succeed",
			"50",
			"",
			"# How many points an attacker must score in a SiegeCamp session to start a siege."),
	WAR_SIEGE_SIEGECAMPS_POINTS_PER_MINUTE(
			"war.siege.siegecamps.points_per_minute",
			"7",
			"",
			"# How many points an attacker town gets per minute, when they are present at the SiegeCamp TimedPointZone."),
	WAR_SIEGE_SIEGECAMPS_DURATION_IN_MINUTES(
			"war.siege.siegecamps.duration_in_minutes",
			"10",
			"",
			"# How many minutes does a SiegeCamp session last?"),	
	WAR_SIEGE_TIMES(
			"war.siege.times",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                         Times                        | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_MAX_HOLDOUT_TIME_HOURS(
			"war.siege.times.max_holdout_time_hours",
			"72",
			"",
			"# The maximum duration a town can hold out against a siege.",
			"# If the value is too high, regular players may be unsatisfied that sieges take too long.",
			"# If the value is too low, casual players may be unsatisfied that ",
		    "#    they are unable to contribute to sieges, especially those involving their own town/nation"),
	WAR_SIEGE_MIN_SIEGE_DURATION_BEFORE_SURRENDER_HOURS(
			"war.siege.times.min_siege_duration_before_surrender_hours",
			"24",
			"",
			"# The minimum duration of a siege before a town can surrender.",
			"# This setting is important because it prevents a 'quick surrender' by the defender",
			"# - which could leave the attacker with no 'aftermath' time in which to execute invade or plunder actions."),
	WAR_SIEGE_MIN_SIEGE_DURATION_BEFORE_ABANDON_HOURS(
			"war.siege.times.min_siege_duration_before_abandon_hours",
			"24",
			"",
			"# The minimum duration of a siege before an attacking nation can abandon.",
			"# This setting is important to prevent an attacker and defender colluding to establish a suitable siege immunity time."),
	WAR_SIEGE_SIEGE_IMMUNITY_TIME_NEW_TOWN_HOURS(
			"war.siege.times.siege_immunity_time_new_town_hours",
			"120",
			"",
			"# This value determines how long a town is safe from sieges, after the town is founded.",
			"# A high value allows more time to fortify new towns, but community engagement by mayors will be slower.",
			"# A low value allows less time to fortify new towns, but community engagement by mayors will be faster."),
	WAR_SIEGE_SIEGE_IMMUNITY_TIME_MODIFIER(
			"war.siege.times.siege_immunity_time_modifier",
			"3",
			"",
			"# This value determines how long a town is safe from sieges, after a siege finishes.",
			"# The actual cooldown time will be the length of the previous siege, multiplied by this modifer.",
			"# A high value makes sieges less frequent. Suitable for moderately-aggressive servers",
			"# A low value makes sieges more frequent. Suitable for highly aggressive servers."),
	WAR_SIEGE_REVOLT_IMMUNITY_TIME_MODIFIER(
			"war.siege.times.revolt_immunity_time_modifier",
			"0.75",
			"",
			"# This value determines how long a town must wait before it can revolt against an occupying nation.",
			"# Revolt immunity beings after a town is defeated in a siege.",
			"# The configured value represents a fraction of the actual immunity time.",
			"# Note: Revolting can break through siege immunity",
			"# WARNING: Do not set this to any higher than about 0.8, because that could lead to towns getting trapped in an endless cycle of invasions from which they could not free themselves."),
	WAR_SIEGE_BANNER_CONTROL_SESSION_DURATION_MINUTES (
			"war.siege.times.banner_control_session_duration_minutes",
			"7",
			"",
			"# This value determines the duration of each banner control session."),
	WAR_SIEGE_DISTANCES(
			"war.siege.distances",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                      Distances                       | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_ZONE_RADIUS_BLOCKS(
			"war.siege.distances.zone_radius_blocks",
			"300",
			"",
			"# The radius of the 'siege zone'.",
			"# This radius applies only horizontally, so players can never get above a siegezone (e.g. to place lava there or something).",
			"# Various siege related effects can apply in this zone e.g. lose points on death, keep inv on death, cannot claim here."),
	WAR_SIEGE_BANNER_CONTROL_VERTICAL_DISTANCE_UP_BLOCKS(
			"war.siege.distances.banner_control_vertical_distance_blocks_up",
			"16",
			"",
			"# This is the vertical distance a soldier must be within above the Banner.",
			"# Note that the horizontal distance is always the same as the Towny townblock size."),
	WAR_SIEGE_BANNER_CONTROL_VERTICAL_DISTANCE_DOWN_BLOCKS(
			"war.siege.distances.banner_control_vertical_distance_blocks_down",
			"4",
			"",
			"# This is the vertical distance a soldier must be within below the Banner.",
			"# Note that the horizontal distance is always the same as the Towny townblock size."),
	WAR_SIEGE_SCORING(
			"war.siege.scoring",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                      Scoring                         | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_BATTLE_POINTS_DISTRIBUTION_WINNER_TAKES_ALL(
			"war.siege.scoring.winner_takes_all_points",
			"true",
			"",
			"# When true, at the end of a successful battle session all points go to the winner of the session.",
			"# When false, the losing side's points are deducted from the winners side, making the losing side's",
			"# efforts during the session matter, and winners gain points slower."),
	WAR_BATTLE_POINTS_FOR_ATTACKER_OCCUPATION(
			"war.siege.scoring.points_for_attacker_occupation",
			"10",
			"",
			"# This setting determines the number of battle points awarded to an occupying attacker.",
			"# The points are awarded if a player remains within a town-block length of the siege banner for: ",
			"# 7 minutes (default configuration)."),
	WAR_BATTLE_POINTS_FOR_DEFENDER_OCCUPATION(
			"war.siege.scoring.points_for_defender_occupation",
			"10",
			"",
			"# This setting determines the number of battle points awarded to an occupying defender.",
			"# The points are awarded if a player remains within a town-block length of the siege banner for ",
			"# 7 minutes (default configuration)."),
	WAR_BATTLE_POINTS_FOR_ATTACKER_DEATH(
			"war.siege.scoring.points_for_attacker_death",
			"150",
			"",
			"# This setting determines the number of battle points awarded if an attacker dies.",
			"# The points are awarded if the player dies within the configured siege zone death radius.",
			"# The points are given to the defending town.",
			"# ",
			"# Background:",
			"# To configure correctly, you must understand how this setting affects a siege:",
			"# 1. Attacker stronger than defender - A stronger attacker is NOT AFFECTED by this value, because regardless of the value, they will expect to score more death points than the opponent.",
			"# 2. Attacker weaker than defender - A weaker attacker IS AFFECTED by this value, because with every attack they will likely suffer a higher death points loss than the opponent.",
			"# ",
			"# Configuration Outcomes:",
		    "# Value HIGH --> If the value is high, then PVP will be DISCOURAGED",
			"# Value LOW --> If the value is low, then PVP will be ENCOURAGED"),
	WAR_BATTLE_POINTS_FOR_DEFENDER_DEATH(
			"war.siege.scoring.points_for_defender_death",
			"150",
			"",
			"# This setting determines the number of battle points awarded if a defender dies.",
			"# The points are awarded if the player dies within the configured siege zone death radius.",
			"# The points are given to the attacking nation.",
			"# ",	
			"# Background:",
			"# To configure correctly, you must understand how this setting affects a siege:",
			"# 1. Defender strong than attacker - A stronger defender is NOT AFFECTED by this value, because regardless of the value, they will expect to score more death points than the opponent.",
			"# 2. Defender weaker than attacker - A weaker defender IS AFFECTED by this value, because with every attack they will likely suffer a higher death points loss than the opponent.",
			"# ",
			"# Configuration Outcomes:",
			"# Value HIGH --> If the value is high, then PVP will be DISCOURAGED",
			"# Value LOW --> If the value is low, then PVP will be ENCOURAGED"),
	WAR_SIEGE_COUNTERATTACK_BOOSTER_EXTRA_DEATH_POINTS_PER_PLAYER_PERCENTAGE(
			"war.siege.scoring.counterattack_booster_extra_death_points_per_player_percentage",
			"10.0",
			"",
			"# As long as the counterattack booster feature is not disabled, this setting determines the strength of the boost.",
			"# Example: If this setting is 10.0, and there are 3 players on the banner control list, and a player from the banner-controlling side dies,",
			"# then the death points awarded to the attacker will be increased by +30%."),
	WAR_SIEGE_BATTLE_SESSION(
			"war.siege.battle_session",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                  Battle Sessions                       | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_BATTLE_SESSION_WEEKDAY_START_TIMES(
			"war.siege.battle_session.weekday_start_times",
			"00:10,01:10,02:10,03:10,04:10,05:10,06:10,07:10,08:10,09:10,10:10,11:10,12:10,13:10,14:10,15:10,16:10,17:10,18:10,19:10,20:10,21:10,22:10,23:10",
			"",
			"# This value determines the weekday times (in Server timezone) when each battle session will start.",
			"# This setting applies to Monday, Tuesday, Wednesday, Thursday, and Friday.",
			"# The format is HOUR:MINUTE.",
			"# The default values are all at ten past the hour, so that the critical point of the battle (the final minutes), will fall on the hour."),
	WAR_SIEGE_BATTLE_SESSION_WEEKEND_START_TIMES(
			"war.siege.battle_session.weekend_start_times",
			"00:10,01:10,02:10,03:10,04:10,05:10,06:10,07:10,08:10,09:10,10:10,11:10,12:10,13:10,14:10,15:10,16:10,17:10,18:10,19:10,20:10,21:10,22:10,23:10",
			"",
			"# This value determines the weekend times (in Server timezone) when each battle session will start.",
			"# This setting applies to Saturday and Sunday.",
			"# The format is HOUR:MINUTE.",
			"# The default values are all at ten past the hour, so that the critical point of the battle (the final minutes), will fall on the hour."),
	WAR_SIEGE_BATTLE_SESSION_DURATION_MINUTES(
			"war.siege.battle_session.duration_minutes",
			"50",
			"",
			"# This value determines the duration of each battle session.",
			"# After a battle session ends,",
			"# the time period until the next battle session starts, is defined as a 'break'"),
	WAR_SIEGE_BATTLE_SESSION_WEEKDAY_MAX_DAILY_PLAYER_BATTLE_SESSIONS(
			"war.siege.battle_session.weekday_max_daily_player_battle_sessions",
			"2",
			"",
			"# This value determines the maximum number of daily battle sessions allowed per player - on week days.",
			"# To disable the limit, set the value to -1.",
			"# This feature mitigates the problem of night-capping, where players stay up all night to gain timed points.",
			"# This feature also mitigates the problem of players skipping weekday school or work to gain timed points."),
	WAR_SIEGE_BATTLE_SESSION_WEEKEND_MAX_DAILY_PLAYER_BATTLE_SESSIONS(
			"war.siege.battle_session.weekend_max_daily_player_battle_sessions",
			"5",
			"",
			"# This value determines the maximum number of daily battle sessions allowed per player - on weekend days.",
			"# To disable the limit, set the value to -1.",
			"# This feature mitigates the problem of night-capping, where players stay up all night to gain timed points."),
	WAR_SIEGE_BANNER_CONTROL_REVERSAL_BONUS(
			"war.siege.banner_control_reversal_bonus",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |           Banner Control Reversal Bonus              | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_BANNER_CONTROL_REVERSAL_BONUS_ENABLED(
			"war.siege.banner_control_reversal_bonus.enabled",
			"true",
			"# This setting determines if the banner control reversal bonus is enabled.",
			"# If enabled, then whenever a team reverses banner control during a battle,",
			"# that team receives a bonus, equal to a multiplier of the timed points which that control had previously granted to the opposing team.",
            "# This feature is particularly important to prevent 'AFK sieging',",
			"# because the more timed points a team gains while its opponent is away,",
			"# the more that team stands to lose if its opponent reappears and reverses banner control."),
	WAR_SIEGE_BANNER_CONTROL_REVERSAL_BONUS_MULTIPLIER(
			"war.siege.banner_control_reversal_bonus.multiplier",
			"2",
			"# This setting determines the strength of the bonus multiplier.",
			"# Example: Assuming this value is 2,",
			"# then if team A has gained 420 battle points from banner control,",
			"# and banner control is then reversed by Team B,",
			"# then Team B will get an instant bonus of 840 battle points."),
	SIEGE_MATERIAL_RESTRICTIONS(
			"siege_material_restrictions",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |              Siege Material Restrictions             | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	SIEGE_MATERIAL_RESTRICTIONS_WILDERNESS_BLOCK_PLACEMENT_PREVENTION_MATERIALS(
			"siege_material_restrictions.wilderness_block_placement_prevention_materials",
			"obsidian, ice",
			"",
			"# This setting is useful to help prevent extreme siege-zone grief such as obsidian forts.",
			"# The list is used to indicate the list of blocks which cannot be placed in the wilderness area of siegezones.",
			"# WARNING: Avoid putting 'common' blocks on this list as that may cause lag."),
	SIEGE_MATERIAL_RESTRICTIONS_WILDERNESS_BUCKET_EMPTYING_PREVENTION_MATERIALS(
			"siege_material_restrictions.wilderness_bucket_usage_prevention_materials",
			"lava_bucket, water_bucket, cod_bucket, pufferfish_bucket, salmon_bucket, tropical_fish_bucket, axolotl_bucket",
			"",
			"# This setting is useful to help prevent extreme siege-zone grief such as obsidian forts or cobble monsters.",
			"# The list is used to indicate the list of forbidden buckets"),
	SIEGE_MATERIAL_RESTRICTIONS_WILDERNESS_EXPLOSION_PREVENTION_ENTITY_TYPES(
			"siege_material_restrictions.wilderness_explosion_prevention_entity_types",
			"primed_tnt, minecart_tnt",
			"",
			"# This setting is useful to prevent the dropping of explosive tnt and tnt-minecarts onto the timed-point-zone.",
			"# This setting is used to indicate the list of entity types which will not explode in the wilderness area of siegezones"),
	WAR_SIEGE_MAP_HIDING(
			"war.siege.map_hiding",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                     Map Hiding                       | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	WAR_SIEGE_MAP_HIDING_ENABLED(
			"war.siege.map_hiding.enabled",
			"true",
			"",
			"# If this setting is true, then the map hiding feature is enabled.",
			"# This feature allow players to disappear from the dynmap, allowing military tactics.",
			"# PREREQUISITE: Dynmap plugin",
			"# ACTIVATION_TIME: When a player meets the conditions for map-hiding, the effect takes a few seconds to activate (same for de-activation).",
			"# BANNER CONTROL EXCEPTION: While a player is capping a banner, map-hiding de-activates for them."),
	WAR_SIEGE_MAP_HIDING_AUTOMATIC_MODE_ENABLED(
			"war.siege.map_hiding.automatic_mode.enabled",
			"true",
			"",
			"# If this setting is true, then the automatic map hiding mode is enabled"),
	WAR_SIEGE_MAP_HIDING_AUTOMATIC_MODE_SCOPE_WILDERNESS(
			"war.siege.map_hiding.automatic_mode.scope.wilderness",
			"false",
			"",
			"# If true, then players are hidden when in wilderness."),
	WAR_SIEGE_MAP_HIDING_AUTOMATIC_MODE_SCOPE_RUINS(
			"war.siege.map_hiding.automatic_mode.scope.ruins",
			"false",
			"",
			"# If true, then players are hidden when in ruins."),
	WAR_SIEGE_MAP_HIDING_AUTOMATIC_MODE_SCOPE_BESIEGED_TOWNS(
			"war.siege.map_hiding.automatic_mode.scope.besieged_towns",
			"true",
			"",
			"# If true, then players are hidden when in besieged towns."),
	WAR_SIEGE_MAP_HIDING_AUTOMATIC_MODE_SCOPE_SIEGEZONES(
			"war.siege.map_hiding.automatic_mode.scope.siegezones",
			"true",
			"",
			"# If true, then players are hidden when in siegezones."),
	WAR_SIEGE_MAP_HIDING_AUTOMATIC_MODE_SCOPE_SIEGEZONES_RADIUS(
			"war.siege.map_hiding.automatic_mode.scope.siegezones_radius",
			"1.0",
			"",
			"# If this setting is 1, then the map-hide radius is the siegezone radius.",
			"# If this setting is not 1, then the map-hide radius is a multiplier ratio of the siegezone radius.",
			"# EXAMPLE: If this setting is 3, then the map-hide radius is siegezone_radius x 3 "),
	WAR_SIEGE_MAP_HIDING_TRIGGERING_ENABLED(
			"war.siege.map_hiding.triggering.enabled",
			"false",
			"",
			"# If this setting is true, then it is possible for individual players to trigger map hiding,",
			"# by equipping a specific combination of items."),
	WAR_SIEGE_MAP_HIDING_TRIGGERING_ITEMS(
			"war.siege.map_hiding.triggering.items",
			"diamond_sword|diamond_sword, diamond_axe|diamond_axe, diamond_shovel|diamond_shovel, bow|bow",
			"",
			"# This config only applies when triggering is enabled",
			"# This list specifies the item combinations which allow players to map-hide.",
			"# Each list entry is in the form of <off-hand>|<main-hand>.",
			"# ",
			"# To specify that both items are required - e.g. 'compass|painting'" + 
			"# To specify that only one item is required - e.g. 'compass|any'",
			"# To specify that one hand must be empty - e.g. 'compass|empty'",
			"# ",
			"# This list allows a server to grant usage of the feature to different categories of players.",
			"# Example 1:  An entry with 'shield|diamond_sword' grants the feature to soldiers.",
			"# Example 2:  An entry with 'compass|diamond_sword' grants the feature to scouts/explorers.",
			"# Example 3:  An entry with 'compass|air' grants the feature to very peaceful explorers.",
			"# Example 4:  An entry with 'compass|any' grants the feature to many players including builders/miners/lumberjacks."),
	SIEGE_DEATH_PENALTY(
			"war.siege.death_penalty",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                Siege Death Penalties                 | #",
			"# +------------------------------------------------------+ #",
			"#                                                          #",
			"# Fyi the keep-env true/false config                       #", 
		    "# is in the switches section above.                        #",
			"############################################################",
			""),
	WAR_SIEGE_DEATH_PENALTY_DEGRADE_INVENTORY_ENABLED(
			"war.siege.death_penalty.degrade_inventory.enabled",
			"true",
			"",
			"# This feature is recommended for use with keep_inventory_on_siege_death.",
			"# If this setting is true, battle will be more 'rpg-like', with a little more death cost.",
			"# If this setting is false, battles will be more 'arcade-like', with low death cost."),
	WAR_SIEGE_DEATH_PENALTY_DEGRADE_INVENTORY_PERCENTAGE(
			"war.siege.death_penalty.degrade_inventory.percentage",
			"20.0",
			"",
			"# This values specifies the percentage equipment degradation that occurs to a soldiers equipment,",
			"# when they die in a siege zone.",
			"# A low value will keep battles fast paced.",
			"# A high value will slow down battles (as players take time to repair items),",
			"# and will also exclude some casual players from war (as they cannot afford to keep repairing/replacing/mending degraded items)"),
	WAR_SIEGE_DEATH_SPAWN_FIREWORK(
			"war.siege.death.spawn_firework",
			"true",
			"",
			"# If enabled, a firework will get spawned whenever a player dies inside a siege zone."),
	PEACEFUL_TOWNS(
			"peaceful_towns",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Peaceful Towns                     | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	PEACEFUL_TOWNS_ENABLED(
			"peaceful_towns.enabled",
			"true",
			"",
			"# If this is true, then a town can toggle peacefulness using /t toggle peaceful,",
			"# ",
			"# By activating SW peacefulness, a town voluntarily gives up all official claims to power over a territory,",
			"# in exchange for complete immunity from attack.",
			"# ",
			"# EFFECTS:",
			"# - Town is immune to siege attack.",
			"# - PVP is forced off in the town (configurable)",
			"# - Residents cannot get nation military ranks.",
			"# - Residents get 'war nausea' if they enter siege zones.",
            "# - Town may get automatically peacefully occupied without a siege.",
			"#   (see user guide for full details)",
			"#"),
	PEACEFUL_TOWNS_CONFIRMATION_REQUIREMENT_DAYS(
			"peaceful_towns.confirmation_requirement_days",
			"5",
			"",
			"# This value determines how long it takes to confirm a town peacefulness status change.",
			"# It is recommended to be high, for use by genuinely peaceful towns, not just for war cost avoidance."),
	PEACEFUL_TOWNS_NEW_TOWN_CONFIRMATION_REQUIREMENT_DAYS(
			"peaceful_towns.new_town_confirmation_requirement_days",
			"2",
			"",
			"# This setting applies only in the first week after a town is founded.",
			"# The value determines the countdown duration to be applied to any peacefulness switch."),
	PEACEFUL_TOWNS_ALLOWED_TO_TOGGLE_PVP(
			"peaceful_towns.allowed_to_toggle_pvp",
			"false",
			"",
			"# If this setting is true, then peaceful towns can toggle PVP on and off."),
	PEACEFUL_TOWNS_SUBVERT_ENABLED(
			"peaceful_towns.subvert_enabled",
			"true",
			"",
			"# If this setting is true, then peaceful subversion (instant occupation) of peaceful towns is enabled."),
	PEACEFUL_TOWNS_REVOLT_ENABLED(
			"peaceful_towns.revolt_enabled",
			"true",
			"",
			"# If this setting is true, then peaceful revolts (instant de-occupation) by peaceful towns are enabled."),
	PEACEFUL_TOWNS_TOWNY_INFLUENCE_RADIUS(
			"peaceful_towns.towny_influence_radius",
			"1200",
			"",
			"# This setting describes a circular area surrounding each peaceful town.",
			"# The peaceful town feels the effect of all 'Towny-Influence' in that area.",
			"# Each nearby automatically generates Towny-Influence in its non-peaceful, non-sieged towns in the area. The value is measured in num-townblocks.",
			"# The nation with the highest Towny-Influence can subvert (peacefully occupy) the peaceful town, if it wishes to do so."),
	OCCUPIED_TOWNS(
			"occupied_towns",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Occupied Towns                     | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	OCCUPIED_TOWN_UNCLAIMING_DISABLED(
			"occupied_towns.occupied_town_unclaiming_disabled",
			"true",
			"",
			"# If this value is true, then a town under occupation cannot unclaim.",
			"#  This setting is recommended, to avoid occupation escape exploits."),
	PUNISH_NON_SIEGE_PARTICIPANTS_IN_SIEGE_ZONE(
			"punish_non_siege_participants_in_siege_zone",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |        Punishing unofficial siege participants       | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	ENABLE_SICKNESS(
			"punish_non_siege_participants_in_siege_zone.enable_sickness",
			"false",
			"",
			"# If true, players that are not participating in a siege will receive war sickness",
			"# A non-participant is a player who does not have a military rank, is not allied to either the attacker or the defender, or is peaceful.",
			"# There are two types of war sickness, full and special.",
			"# Special war sickness is only given if a non-participant is at his town that happened to be in a siege zone",
			"#   - Effects: Weakness V",
			"# Full sickness is given to all players that are not allied to either side, do not have a military rank, or is peaceful, and are not in their own town.",
			"#   - Effects: Nausea V, Poison V, Weakness V, Slowness III, Mining Fatigue III"
	),
	SECONDS_BEFORE_SICKNESS(
			"punish_non_siege_participants_in_siege_zone.seconds_warning",
			"5",
			"",
			"# This is how many seconds a player has to leave the siege zone before he gets war sickness",
			"# If this is set to 0, no warn will be given and non-participants will receive war sickness instantly, if enabled"
	),
	CANNONS_INTEGRATION(
			"cannons_integration",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                 Cannons Integration                  | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	CANNONS_INTEGRATION_ENABLED (
			"cannons_integration.enabled",
			"false",
			"",
			"# If this value is true, then the integration with the Cannons plugin is enabled.",
			"# The integration works as follows:",
			"#  - Town cannons cannot be fired unless there is a 'cannon session' in effect.",
			"#  - A cannon session starts/refreshes when a town resident with the 'siegewar.town.siege.startcannonsession' fires a town cannon.",
			"#  - While a cannon session is in effect, town cannons can be fired, and town explosion perm protections are forced off.",
			"#  - The cannon session usually lasts just a few minutes (don't make it too long or the defender will often be too scared to fire).",
			"#  - The max duration is configured below.",
			"# "),
	CANNONS_INTEGRATION_MAX_CANNON_SESSION_DURATION(
			"cannons_integration.max_cannon_session_duration",
			"9",
			"# This value determines the max duration of each cannon session,",
			"# The duration is 'in short ticks', typically a short tick is 20 seconds."),
	BEACON_MARKERS(
			"beacon_markers",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Beacon Markers                     | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	BEACON_MARKERS_ENABLED(
			"beacon_markers.enabled",
			"true",
			"",
			"# If enabled, client-side beacons will be shown for players at the siege banner while they are in a siege zone."),
	BEACON_MARKERS_CAPTURE_COLOR(
			"beacon_markers.capture_color",
			"yellow",
			"",
			"# The color that the beacon will be while a player is capturing it. Only visible to the player.",
			"# Accepts any of the following colors (case insensitive): White, Orange, Magenta, LightBlue, Yellow, Lime, Pink, Gray, LightGray, Cyan, Purple, Blue, Brown, Green, Red & Black.",
			"# Defaults to yellow if no valid color is entered."),
	BEACON_MARKERS_CAPTURED_COLOR(
			"beacon_markers.captured_color",
			"green",
			"",
			"# The color that the beacon will be for a player when their side has control of the banner.",
			"# See above for valid colors.",
			"# Defaults to green if no valid color is entered."),
	BEACON_MARKERS_ENEMY_COLOR(
			"beacon_markers.enemy_color",
			"red",
			"",
			"# The color that the beacon will be for a player when the enemy side has control of the banner.",
			"# See above for valid colors.",
			"# Defaults to red if no valid color is entered."),
	BANNER_XYZ_TEXT(
			"banner_xyz_text",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                   Banner XYZ Text                    | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	BANNER_XYZ_TEXT_ENABLED(
			"banner_xyz_text.enabled",
			"false",
			"# The banner xyz text is an alternative to beacon markers for siege banners (but they can also be used together).",
			"# If enabled, besieged towns will show the XYZ of the siege banner on their town screens."),
	NATION_SIEGE_IMMUNITY(
		"nation_siege_immunity",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                 Nation Siege Immunity                | #",
			"# +------------------------------------------------------+ #",
			"############################################################",
			""),
	NATION_SIEGE_IMMUNITY_ENABLED(
			"nation_siege_immunity.enabled",
			"false",
			"",
			"# If this setting is true, then nation siege immunity is enabled.",
			"# ",
			"# This feature gives each nation regular breaks from war, ",
			"# by granting siege-immunity to all their towns after a home-defence war.",
			"# ",
			"# A home-defence war is a period in which one or more of a nation's towns are under siege.",
			"# ",
			"# NOTES:",
			"# 1. To mitigate exploits, nations suffer some mild negative effects while fighting a home-defence war - cannot claim/unclaim/recruit.",
			"# 2. To mitigate annoyance-sieges, the cost to attack a nation's towns increases as that nation increases in size.",
			"# 3. If a town switches nation during a home-defence war",
			"#     then when the home-defence war ends, the post-war immunity from that town,",
			"#     is distributed between all the nations which the town had during the siege",
			"#     (but not any occupying nation)."),
	NATION_SIEGE_IMMUNITY_DURATION_MODIFIER(
			"nation_siege_immunity.duration_modifier",
			"0.5",
			"",
			"# This setting determines the duration of siege immunity which each nation town receives after a home defence war.",
			"# ",
			"# FORMULA:",
			"# Nation-Town Immunity Duration = Total Duration of Sieges x This Value.",
			"# ",
			"# EXAMPLE:",
			"# A nation suffers a big home defence war, of 4 sieges, with each siege lasting 3 days.",
			"# This gives a Total Siege Duration of 12 days",
			"# If this value is 0.5, then immunity duration will be 6 days",
			"# Thus when the war ends, each non-besieged nation town will get 6 days of siege immunity."),
	NATION_SIEGE_IMMUNITY_HOME_TOWN_CONTRIBUTION_TO_ATTACK_COST(
			"nation_siege_immunity.home_town_contribution_to_attack_cost",
			"0.1",
			"",
			"# If this setting is higher than 0,",
			"# then the larger a nation is, the higher the cost to attack one of its towns.",
			"# ",
			"# This setting is important to mitigate 'annoyance sieges', ",
			"# because large nations are disproportionately affected by the mild home defence war restrictions.",
			"# Thus without mitigation, small nations could attack larger ones,",
			"# with no intention of fighting, but just to cheaply disrupt them.",
			"# ",
			"# EXAMPLE:",
			"# If this setting is 0.1,",
			"# and an attack is attempted on a nation town,",
			"# then for every natural town (i.e. not occupied foreign towns) in that nation,",
			"# the attack-cost (i.e. warchest) requirement is increased by 10% of the amount it would take to attack that town."),
	BANNER_CONTROL(
		"banner_control",
			"",
			"",
			"",
			"############################################################",
			"# +------------------------------------------------------+ #",
			"# |                    BANNER CONTROL                    | #",
			"# +------------------------------------------------------+ #",
			"#                                                          #",
			"# FYI: Most banner-control-related settings are above,     #",
			"# and not in this section.                                 #",
			"############################################################",
			""),
	BANNER_CONTROL_CAPTURE_MESSAGE_COLOR(
			"banner_control.capturing_message_color",
			"yellow",
			"",
			"# This setting determines the color of the boss bar message,",
			"# which players see while they are capturing the banner.");

	private final String Root;
	private final String Default;
	private String[] comments;

	ConfigNodes(String root, String def, String... comments) {

		this.Root = root;
		this.Default = def;
		this.comments = comments;
	}

	/**
	 * Retrieves the root for a config option
	 *
	 * @return The root for a config option
	 */
	public String getRoot() {

		return Root;
	}

	/**
	 * Retrieves the default value for a config path
	 *
	 * @return The default value for a config path
	 */
	public String getDefault() {

		return Default;
	}

	/**
	 * Retrieves the comment for a config path
	 *
	 * @return The comments for a config path
	 */
	public String[] getComments() {

		if (comments != null) {
			return comments;
		}

		String[] comments = new String[1];
		comments[0] = "";
		return comments;
	}

}
